### ISSUE TITLE
Text colours in Playgrounds section should follow other parts of the UI

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#1004]
![Screenshot 2024-04-24 at 8 12 01 PM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6422176/ca70c93b-7c76-4542-9f9f-30dc8a0f3476)

In the above example, the "User" and "Assistant" titles are OK.

But the information within the box should be gray which would follow the rest of the UI. 

Typically throughout the UI of PD / extensions, it looks like white is reserved for titles, but gray for the inner parts.

**Comment by slemeur** [comment]
Closing as obsolete
