### ISSUE TITLE
There is no model yet -> There are no models yet

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#1005]
Should be "there are no models yet"

![Screenshot 2024-04-24 at 10 32 01 PM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6422176/4be6fb68-5dd2-429b-b285-8ab101c3284d)

**Comment by axel7083** [comment]
Fixed by https://github.com/containers/podman-desktop-extension-ai-lab/pull/1042
