### ISSUE TITLE
No Podman machine running banner should not be displayed on Linux

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#1022]
We currently get the first running connection to detect if there is a podman machine running but on linux this is not mandatory.

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/49404737/6509f481-549e-4e3f-8044-974db5509a6e)

**Comment by odockal** [comment]
@ScrewTSW I think it was settled that the podman.service is not running properly?
