### ISSUE TITLE
Llamacpp server fails to start on windows

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-ai-lab#1031]
It seems that there is some issue with starting up the Chatbot and Codegen apps in Ai Lab, cause by an issue with llamacpp-server not being able to start up on Windows operating system.

![image (2)](https://github.com/containers/podman-desktop-extension-ai-lab/assets/106525396/a80b7459-2926-45a8-863c-3735891cebbc)

Steps:

1. Be on Windows OS 11.
2. Have PD 1.10.1 installed.
3. Install AI Lab v1.0.0.
4. Try to start up Chatbot or Codegen apps.
5. Llamacpp-server can fail to start.

**Comment by ScrewTSW** [comment]
![podman_desktop_bgaemcxupv.png](https://github.com/containers/podman-desktop-extension-ai-lab/assets/16451875/d91a676d-e6ee-46e3-868f-cb98df1c2d8f)

Similar failure, Win 10 22H2, podman 5.0.2 default machine

**Comment by lstocchi** [comment]
> Similar failure, Win 10 22H2, podman 5.0.2 default machine

@ScrewTSW in your case it fails to upload the model. What we do is to copy the model inside the podman machine. Do you have enough space in your computer (it wil ltake twice the space of the model)? Or, can you ssh inside your machine?

**Comment by lstocchi** [comment]
Just to keep note of my tests.
On my machine it works fine.
To ensure it was not something i had cached, i created a new hyper-v machine, installed wsl, installed podman, create a new podman machine, downloaded the recipes repo (v1.1.0 tag), built the image. It worked fine

**Comment by cbr7** [comment]
@lstocchi can you check what pip version gets used when you build the llamacpp locally, if the command you pasted in the slack yesterday? Because for me it's using pip 22.2.2 even though installed on my machine there is pip 24.

**Comment by benoitf** [comment]
https://github.com/containers/ai-lab-recipes/pull/457

**Comment by benoitf** [comment]
you can try with this Containerfile

**Comment by cbr7** [comment]
Yeah, that works.
