### ISSUE TITLE
check git repository when ref is a tag fails

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#1038]
When the `ref` of a recipe is a tag, the check of the repository _integrity_ fails, as the `ref` is compared with the commit id and not the tag name 

![git-check-fails](https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/492daee7-4050-4c0d-a170-63e1e439aa80)

**Comment by benoitf** [comment]
looks like a blocker for 1.1 ?
