### ISSUE TITLE
Running recipe does not have a stop action

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#1070]
### Is your enhancement related to a problem? Please describe

I'm going to open this issue as we received a comment from a user about not understanding why a running recipe does not have a `stop` action. I think this is not the first time we receive this feedback (i cannot find the other issue though) so we can use this issue to discuss what we want to do about it. Maybe we can improbe the UX just adding a tooltip or updating the icon.

original -> https://github.com/containers/podman-desktop-extension-ai-lab/issues/1068#issuecomment-2100569114
```
It doesn't relate to the model list, but when viewing an AI App, after starting it up, 
it would make sense to me to offer a way to stop it from that page. 
I see controls to Delete, Open, or Restart, but what about if I'm done running it and
just want to turn it off? I can go to Pods, and that has a Stop button, but it would 
be quicker if there were some way from the app page. Similarly, there's no way to 
Stop from the Running AI Apps list, just Delete, Open, or in the overflow - Restart, 
and Open Recipe.
```

### Describe the solution you'd like

N/A

**Comment by mattreid** [comment]
Is there something I can click from that page already to do what I'm suggesting and I'm just not realizing it from the terminology? What action in the UI would you recommend when I'm done with the AI app for now, but may want to run it later (so I don't want to delete it and have to re-download next time I want to run it)? 

in #1068 you mentioned that a pod doesn't have the concept of stopping/pausing, and you wanted to match that here, but when I visit the Pods list in Podman Desktop, there's a stop button on the pod. Maybe that is something else on the backend, but if Pods offer it in the UI, perhaps the same functionality should be offered from AI Labs? 
![Screenshot 2024-05-08 at 9 52 29 AM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/1242413/712d618d-092f-4cb8-9b1c-eca68012c0b6)
