### ISSUE TITLE
can't pull ai-lab-playground-chat image when creating model service 

### ISSUE THREAD

**Issue by jchenibm** [containers/podman-desktop-extension-ai-lab#1079]
### Bug description

When creating a new model service, throw the follwing error:

Something went wrong while trying to create an inference server Error: access to image "ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1" is denied (500 error). Can also be that the registry requires authentication..

Need account & login?

Env: Windows 10, podman-desktop: v1.10.2

### Operating system

Windows 10

### Installation Method

from Podman-Desktop extension page

### Version

1.0.0

### Steps to reproduce

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11772643/99942d12-8e66-4c6d-991d-8a058b779231)

**Comment by benoitf** [comment]
Hello @jchenibm what happens if you do

```
podman pull ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1
```

**Comment by benoitf** [comment]
the image is there https://github.com/containers/podman-desktop-extension-ai-lab-playground-images/pkgs/container/podman-desktop-extension-ai-lab-playground-images%2Fai-lab-playground-chat

**Comment by jchenibm** [comment]
> Hello @jchenibm what happens if you do
> 
> ```
> podman pull ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1
> ```
> 
> using the command line

@benoitf please see the error in CLI:

```
$podman pull ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1

Trying to pull ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1...
Error: initializing source docker://ghcr.io/containers/podman-desktop-extension-ai-lab-playground-images/ai-lab-playground-chat:0.3.1: pinging container registry ghcr.io: Get "https://ghcr.io/v2/": proxyconnect tcp: EOF
```

Thanks a lot!

**Comment by jchenibm** [comment]
Connectivity & proxy issue. I can download the images now. Thanks!
