### ISSUE TITLE
After 10-20 questions the chatbot app is no longer working

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-ai-lab#1083]
### Is your enhancement related to a problem? Please describe

ask many questions like
"What is Podman Desktop" (waiting each time to get the answer)

After that you get an error or application hangs and consume all the CPU

### Describe the solution you'd like

No error or being properly asked to restart the app

**Comment by benoitf** [comment]
I had this error sometimes but here I got

```
Llama.generate: prefix-match hit
```
in the logs

```
Llama.generate: prefix-match hit
INFO:     127.0.0.1:40230 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40232 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50622 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50638 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40224 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:57906 - "GET / HTTP/1.1" 404 Not Found
```

and then all CPU is eaten but I never get an answer

**Comment by benoitf** [comment]
but yes at summit I faced the `Requested tokens exceed context window` error

**Comment by MichaelClifford** [comment]
OK, I think we can fix the context window issue. But I'm not sure about the "all-cpu-no-answer" issue. What hardware are you using?

**Comment by benoitf** [comment]
forgot to hit send, hardware is Apple M2 Max
but I think I only reached once the 'no reply'

I think also https://github.com/containers/podman-desktop-extension-ai-lab/issues/1082 is more important

**Comment by MichaelClifford** [comment]
@benoitf please see https://github.com/containers/ai-lab-recipes/pull/495

**Comment by lstocchi** [comment]
We should show an error message if the user exceed the token limit
