### ISSUE TITLE
Add function calling support

### ISSUE THREAD

**Issue by sebastienblanc** [containers/podman-desktop-extension-ai-lab#1116]
### Is your feature request related to a problem? Please describe

Function calling is getting more and more popular and open up to some crazy use cases. 

### Describe the solution you'd like

In models that support function calling, the openAI API "wrapper" should return the correct json structure containing the "tools" response. 

### Additional context

I know you've put that on the roadmap on the readme but I didn't find any issue to upvote it, so here it is :) 
Awesome extension btw ! 

Sub tasks:
- [x] https://github.com/containers/podman-desktop-internal/issues/324
- [x] #1771
- [x] #1772
- [x] #1831

**Comment by slemeur** [comment]
Thanks Sebi!!

**Comment by kdubois** [comment]
+1 !

**Comment by jeffmaury** [comment]
See https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/Functions.ipynb for an example

**Comment by axel7083** [comment]
This is an epic task, as a lot of requirement to enable it, the first one being the scope of this feature, as "Add function calling support" is very vague, and the example provided does not really cover how we want to expose this in AI Lab, some questions:
- Do we want to have a dedicated page allowing users to experiment with it ?
- How to we tell a model has function calling feature ?
- Do we allow function calling in the playground ?

This need discussion.

**Comment by lstocchi** [comment]
Discussed with Jeff. As first steps we have to find a model with function calling support, add it on the catalog (a property will allow us to identify a model with function calling support), then create/add a recipe that leverage it.

**Comment by sebastienblanc** [comment]
@lstocchi Excellent, any Mistral model starting from 0.3 supports Function Calling, that could be one of the candidates ?

**Comment by lstocchi** [comment]
@sebastienblanc I guess so, we'll talk with @slemeur when he comes back from PTO

**Comment by jamesfalkner** [comment]
FYI Granite 20B now has a functioncalling variant. https://huggingface.co/ibm-granite/granite-20b-functioncalling

**Comment by kdubois** [comment]
Any idea when this could be planned? This is a huge missing feature to promote Podman AI Lab vs Ollama for local development in our conference sessions and labs

**Comment by kdubois** [comment]
For reference: https://ollama.com/blog/tool-support

**Comment by jeffmaury** [comment]
Next release will push the date ASAP

**Comment by axel7083** [comment]
This is not completed

**Comment by axel7083** [comment]
We need to have a recipe, a compatible model in the catalog and some documentation
