### ISSUE TITLE
Add a state/indicator to show more info about the recipe

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#1120]
### Is your enhancement related to a problem? Please describe

Taken from https://github.com/containers/podman-desktop-extension-ai-lab/issues/843 to split that issue. 

Also I would expect to have the state/indicator for each recipe card (like if I already have cloned the repository or not)

### Describe the solution you'd like

To be discussed if we have to add an icon, or a text message or a different color to show a specific state

**Comment by ekidneyrh** [comment]
Hi Luca! What would the different states be for this? Is it just if the repo is cloned or not? Is it just once the repo can be cloned? And is this for the recipe detail page, or something to be seen on the cards in the catalog?

**Comment by ekidneyrh** [comment]
Discussed this during the UX call yesterday. Suggested states are to know if cloned, ready to be used or already looked at.
One option we could look at is having it similar to model pages, with tabs across the top to organize.

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/aa716a14-56b3-42bc-8506-fb9e25f9b092)

Or we could do something like the extensions catalog and how it shows already installed, customizing it to say already cloned etc.

I think this ticket along with https://github.com/containers/podman-desktop-extension-ai-lab/issues/1126 would benefit from a revamped recipe catalog page.

**Comment by axel7083** [comment]
Closing as resolved
