### ISSUE TITLE
Importing a models on a fresh instance lead to an error when writing `user-catalog.json` file

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1132]
### Bug description

When importing a model, we are writing the `user-catalog.json` file in the AI Lab storage as shown bellow

https://github.com/containers/podman-desktop-extension-ai-lab/blob/529bc5bef181032081fb5a616c0de7afabd27c4e/packages/backend/src/managers/catalogManager.ts#L229

However, we do not mkdir the parent directory, most of the time it will be fine, as other mechanism will create the folder (download a model, checkout recipe etc.) but in a fresh instance, it will lead to an error

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

See above

**Comment by pilhuhn** [comment]
Just for the record: same issue on macOS, where it was originally detected.
