### ISSUE TITLE
Experiment Instructlab on Windows/WSL/GPU

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1146]

**Comment by axel7083** [comment]
To give a summary of my experience, I was able to generate a lot of data from a given markdown.

I took a markdown file as source from a repository describing a CLI tool. Something barely known, and not really public. To ensure the model had no idea prior I asked question about it, and it was not aware of it.

The data generated was 50/50 garbage/ok: it was generating completely irrelevant question and absurd answer comparing to the documetantion.

Main issues:
- it was inventing flags/arguments that were not documented nor exists
- it was combining commands arguments and flag when it was clearly impossible
- The question were not relevant to the usage

It was very slow overall, I spent **hours** configuring the GPU on the WSL/fedora.
