### ISSUE TITLE
Automatically remove services when models are deleted.

### ISSUE THREAD

**Issue by tombenninger** [containers/podman-desktop-extension-ai-lab#1158]
### Is your enhancement related to a problem? Please describe

When you delete a model in the catalog, including imported models, it can leave services configured.

### Describe the solution you'd like

It should warn and prompt the user to automatically stop and delete the related services to keep things clean.

### Describe alternatives you've considered

Manually managing services, but this can be difficult with existing information if you have a lot of models and services configured for testing.

**Comment by axel7083** [comment]
Related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/791
