### ISSUE TITLE
Model catalog importing and sorting

### ISSUE THREAD

**Issue by tombenninger** [containers/podman-desktop-extension-ai-lab#1159]
### Is your enhancement related to a problem? Please describe

Models are typically sorted alphabetically by source namespace, except when you import a model:

![Screenshot 2024-06-04 at 9 29 15 AM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6990085/4c74e462-cbfd-4a82-9c9f-bf2a5e9ddd9a)

When you import a model, you have to give it a name to be sorted by:
![Screenshot 2024-06-04 at 9 46 05 AM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6990085/91573a6f-d4e2-41d6-887e-5d51a4381bb5)

This can lead to models being harder to find.

### Describe the solution you'd like

Have the import form updated to default to naming the entry `local-import/<model name>` instead of just `<model-name>` (or something similar) or perhaps have it be a separate field to provide the import namespace.

### Describe alternatives you've considered

Users can do this themselves, but there is no default or prompted namespace and they probably won't realized the need until after running into sorting issues.

**Comment by axel7083** [comment]
We updated the way we sort models by default, with the following rules:

- At the top, the models in use (inference servers)
- Then the models downloaded
- Finally models available

See https://github.com/containers/podman-desktop-extension-ai-lab/pull/851 for ref
