### ISSUE TITLE
Descriptions on Model Parameters

### ISSUE THREAD

**Issue by lkerriso** [containers/podman-desktop-extension-ai-lab#1194]
### Is your feature request related to a problem? Please describe

Users do not know what temperature, Max Tokens, and Top-P mean when adjusting their Model Parameters. 

### Describe the solution you'd like

I think the features desgin should include quick descriptions. Example: Top-P:Range of Vocabulary. Then have it on a spectrum from Relevance to Diversity. 

### Additional context

![Group 5](https://github.com/containers/podman-desktop-extension-ai-lab/assets/171864915/468e4e7d-4353-4f04-98bc-0705fc454e56)
I attached a design I think could be cool.

**Comment by jeffmaury** [comment]
Duplicates #847
