### ISSUE TITLE
epic: light mode in AI Lab

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1209]
## Components

- [x] chore: light mode Navigation Menu: https://github.com/containers/podman-desktop-extension-ai-lab/pull/1208
- [x] chore: light mode NavPage: https://github.com/containers/podman-desktop-extension-ai-lab/issues/973
- [x] #1271
- [x] #1282
- [x] #1283

## Pages

- [x] #1249
- [x] #1251
- [x] #1253
- [x] #1254
- [x] #1256
- [x] #1259
- [x] #1261
- [x] #1263
- [x] #1270
- [x] #1274
- [x] #1284
- [x] #1285
- [x] #1286

**Comment by slemeur** [comment]
Closing
