### ISSUE TITLE
Improve recipe path readability on recipes list

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1214]
### Is your enhancement related to a problem? Please describe

Following discussion on https://github.com/containers/podman-desktop-extension-ai-lab/pull/1199

The current path uses `text-ellipsis` to hide the overflow.

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/63d04228-07a2-4503-877c-3bfc48e75076)

### Auto horizontal scroller on hover

https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/ee2c9867-ce3e-47c1-bf74-62430b62e3b6

branch ref https://github.com/axel7083/ai-studio/tree/feature/hover-scroller-component

### Tooltip

Tooltip is a bit complicated, as the path is a bit long, so in a lot of cases the tip is partially hidden, and we could try enforcing the position, but depending on the position of the grid, we are facing different overflow problem.

### Copy cursor

In addition of the path, user will probably want to copy it, we might replace the default cursor by a copy icon, and allow on click to add it to the clipboard.

**Comment by slemeur** [comment]
Closing in favor of https://github.com/containers/podman-desktop-extension-ai-lab/issues/1980
