### ISSUE TITLE
Initial releasable light mode support

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-ai-lab#1235]
### Is your enhancement related to a problem? Please describe

Epic #1209 covers full light mode support for AI Lab, but when adopting the Podman Desktop UI components and starting to support light mode directly this path goes though an ugly middle period where things are unusable if Podman Desktop is in light mode b/c the extension will be in a mix of light and dark (e.g. light labels on light backgrounds), or just jarringly distracting.

### Describe the solution you'd like

This is a placeholder to find the first shippable middle ground, i.e. listing the core set of issues that need to be complete (UI component issues + native AI Lab issues) so that the core of AI Lab is working in light mode and usable, and can be released at any time, and any remaining issues can be done individually or in smaller groups.

### Describe alternatives you've considered

Force dark mode for UI components in releases until we pass through this period, or document not to use with light mode.

**Comment by jeffmaury** [comment]
What is the difference of this compared to #1209

**Comment by deboer-tim** [comment]
#1209 is the full set of issues needed to support light mode, but we're doing a release of Podman Desktop now without everything complete (https://github.com/containers/podman-desktop/issues/4914), and ditto for bootc (https://github.com/containers/podman-desktop-extension-bootc/issues/536).

The important bit as you start adopting @podman-desktop/ui-svelte components or light mode is that you go through a phase where some things are (e.g.) 'white on light' and hence completely unusable, ugly, or unshippable. I just wanted to make sure we identify this critical subset of the issues and assign them to this sprint (and then close this), so that we move through this period quickly. I can do that late this week if that helps.

**Comment by nichjones1** [comment]
closed as the final issue has been created and assigned to Axel in sprint 259
