### ISSUE TITLE
Model Catalog: Delete feature option

### ISSUE THREAD

**Issue by cedricclyburn** [containers/podman-desktop-extension-ai-lab#1294]
### Is your enhancement related to a problem? Please describe

When I'm using AI Lab, I've got some imported GGUF model files from InstructLab, but sometimes need to delete them from the catalog. It's a bit frustrating that the only option to remove from AI Lab is to delete the entire model file itself. What if I'm using the same gguf file for another purpose?

<img width="1241" alt="Screenshot 2024-06-26 at 3 36 09 PM" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/54345140/2f91f157-d1fa-42a9-9fba-7074442a642d">

### Describe the solution you'd like

Maybe an option to remove imported model from catalog but don't delete the actual file :D

**Comment by jeffmaury** [comment]
Duplicates #934
