### ISSUE TITLE
UX: Integration of InstructLab

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1300]
This issue is dedicated to building the mockups to integrate InstructLab in Podman AI Lab

- [x] #1380

**Comment by ekidneyrh** [comment]
Left some Qs on https://github.com/containers/podman-desktop-extension-ai-lab/issues/1380

**Comment by MariaLeonova** [comment]
I commented in https://github.com/containers/podman-desktop-extension-ai-lab/issues/1380 and in the file containing mockups.

**Comment by MariaLeonova** [comment]
I just want to point out that some discussions around the UX flow details are still ongoing.
