### ISSUE TITLE
Start AI app button on custom user-catalog.json recipe does nothing.

### ISSUE THREAD

**Issue by alxlenc** [containers/podman-desktop-extension-ai-lab#1379]
### Bug description

I'm not able to start a custom AI recipe by modifying a pre-existing recipe. Following the extension's README, I created user catalog `$HOME/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/user-catalog.json` to create a ChatBotTest recipe. I copied the [defatul catalog](https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/packages/backend/src/assets/ai.json)  and left only the chatbot recipe with modifications the `id` and the `name` recipe properties to avoid collisions.

The extension immediately reloads the catalog list but when I click `Sart AI App` on my chatbot version nothing happens. I tried searching on Podman Desktop's logs and no error shows. The default recipes continue to work at this point.

![image](https://github.com/user-attachments/assets/27a81f8c-0f3e-4e7d-8b23-9902d8ca6acb)

### Operating system

Fedora 40

### Installation Method

from Podman-Desktop extension page

### Version

1.0.0

### Steps to reproduce

1. Add a simplified version of the default catalog with only one recipe with it's id and name modified to avoid collisions.
2. Click `Start AI App` and nothing happens.

### Additional context

Versions:

- podman-desktop-extension-ai-lab v1.1.2 (The issue form only offered v1.0.0) 
- podman-desktop v1.11.1 Flatpak installation.

**Comment by axel7083** [comment]
Closing as resolved with the owner of the issue. The issue was, he was using `v1.1.2` which were not supporting the `recommended` property in the recipe property
