### ISSUE TITLE
Propose a workflow for integrating InstructLab in Podman AI Lab

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1380]
Proposition:

- from the models list, you have a Fine Tune action. It should start a workflow/wizard/dialog asking from a skill/knowledge repository and start an InstructLab session.
- A new InstructLab panel will be added that list all fined tuning sessions and their state
- Once a session is completed, a new model will be automatically added to the list of models.
- We should be able to distinguish fine tuned models through a specific label
- Fine tuning sessions should be saved and restarted

**Comment by ekidneyrh** [comment]
I have a few questions on some of the points mentioned.

> From the models list, you have a Fine Tune action. It should start a workflow/wizard/dialog asking from a skill/knowledge repository and start an InstructLab session.

Does this mean in the menu bar at the side or as a button on the top right of the models screen? And is the dialog like a form requesting data entry from the user?

> A new InstructLab panel will be added that list all fined tuning sessions and their state

Where does this get added? To the models page? Or to the form / dialog mentioned above? What triggers this to appear? 

> We should be able to distinguish fine tuned models through a specific label

Could this be something that can be filed with the tabs on the top of the page?

**Comment by jeffmaury** [comment]
> I have a few questions on some of the points mentioned.
> 
> > From the models list, you have a Fine Tune action. It should start a workflow/wizard/dialog asking from a skill/knowledge repository and start an InstructLab session.
> 
> Does this mean in the menu bar at the side or as a button on the top right of the models screen? And is the dialog like a form requesting data entry from the user?

I was thinking as an additional action in the menu bar. Yes at least the path to the knowledge/skills repo
> 
> > A new InstructLab panel will be added that list all fined tuning sessions and their state
> 
> Where does this get added? To the models page? Or to the form / dialog mentioned above? What triggers this to appear?
No as a new navbar item (like Running, Catalog,....)
> 
> > We should be able to distinguish fine tuned models through a specific label
> 
> Could this be something that can be filed with the tabs on the top of the page?
On the models pages, yes we can have an additional 'Fine tuned' tab

**Comment by MariaLeonova** [comment]
@jeffmaury @ekidneyrh I have left several comments in the [Penpot mockup](https://design.penpot.app/#/workspace/971a4169-b56c-80d0-8002-4ff987ca8805/6e12068a-09a0-801a-8004-24b355541870?page-id=920879a4-639b-802b-8004-b471f6ac8396).

Couple of things I'd like to point out (these are left as comments on relevant screens in the penpot file, too):
 - the flow is nice and clean
 - users are expected to add knowledge and skills by uploading a YAML file from their home directory
 - would they be familiar with InstructLab and concept of skills at this point?
 - how would the YAML files be created (for skills and knowledge)?
 - should this mimic in anyway the skill submission flow on InstructLab itself or will this be separate? Ho will the integration work from the technical POV?
 - can more guidance be provided to help users along the way? I.e. example URLs / sample YAML files, etc.
 - where shall the fine-tuned icon appear next to the model? On the model list?

**Comment by MariaLeonova** [comment]
@ekidneyrh separate UI question - is there a specific library that's used for icons in Podman desktop?

**Comment by ekidneyrh** [comment]
> @ekidneyrh separate UI question - is there a specific library that's used for icons in Podman desktop?

They are sort of mixed at the moment. Some are from libraries and some are custom. I have a ticket here for tracking them https://github.com/containers/podman-desktop/issues/7655 so we can have them all in one place. We also need to have them using stroke instead of being filled, so the line weight can be edited easily in the code. The ticket for that is here: https://github.com/containers/podman-desktop/issues/8043

**Comment by jeffmaury** [comment]
> @jeffmaury @ekidneyrh I have left several comments in the [Penpot mockup](https://design.penpot.app/#/workspace/971a4169-b56c-80d0-8002-4ff987ca8805/6e12068a-09a0-801a-8004-24b355541870?page-id=920879a4-639b-802b-8004-b471f6ac8396).
> 
> Couple of things I'd like to point out (these are left as comments on relevant screens in the penpot file, too):
> 
>     * the flow is nice and clean
Cool to know
> 
>     * users are expected to add knowledge and skills by uploading a YAML file from their home directory
> 
>     * would they be familiar with InstructLab and concept of skills at this point?
That was part of the design asking users to provide those files is a way to introduce them to these concept, maybe we can add a link to InstructLab documentation if they need more information
> 
>     * how would the YAML files be created (for skills and knowledge)? is this the file they have downloaded from the InstructLab after submitting a skill there?
Those files need to be provided by users, it's out of scope for this first iteration
> 
>     * should this mimic in anyway the skill submission flow on InstructLab itself or will this be separate? Ho will the integration work from the technical POV?
I don't know the flow but I think it's is to simplify the PR creation on the InstructLab repo, but I may be wrong
> 
>     * can more guidance be provided to help users along the way? I.e. example URLs / sample YAML files, etc.
See my comment above
> 
>     * where shall the fine-tuned icon appear next to the model? On the model list?
Yes
> 
>     * can a model be fine-tuned in any other way?
Not from the Podman AI Lab UI as of yet

**Comment by ekidneyrh** [comment]
> Okay! So if I were to suggest and icon for a fine-tuned model, there aren't strict guidelines? Could you please point me to where icons currently can be found - for reference.

They are scattered around the place atm :see_no_evil: they are in svelte form here https://github.com/containers/podman-desktop/tree/main/packages/renderer/src/lib/images

Here are some tickets i found:

https://github.com/containers/podman-desktop/issues/7641
https://github.com/containers/podman-desktop/issues/7287
https://github.com/containers/podman-desktop/issues/7680
https://github.com/containers/podman-desktop/issues/7378
