### ISSUE TITLE
Provide a tooltip for the path displayed in the list of recipes

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1482]
### Bug description

The recipe list is now showing the path where a recipe has been cloned.
Unfortunately, the path is too long and there is no way to see it all.

<img width="1699" alt="Screenshot 2024-08-06 at 09 31 07" src="https://github.com/user-attachments/assets/262c5786-ba92-4f8a-9358-7105460ff60e">

There should be a tooltip that is at least showing "Cloned at path: <path>"

Finally, what's the value of displaying this path here? Is the user supposed to be able to copy it?
Shouldn't it be in the recipe's details, rather than on the catalog? 

### Operating system

Ventura

### Installation Method

None

### Version

next (development version)

**Comment by axel7083** [comment]
Duplicates of https://github.com/containers/podman-desktop-extension-ai-lab/issues/1214
