### ISSUE TITLE
all breadcrumbs are broken

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1492]
### Bug description

![image](https://github.com/user-attachments/assets/ad392ac9-ec44-4e59-bca7-8e1079a8058a)

Nothing is happening when I click on recipes

![image](https://github.com/user-attachments/assets/d75e61b3-46af-41d4-a141-16a36699181d)

Nor model services

![image](https://github.com/user-attachments/assets/1d98ec7a-defe-4b3c-bbb0-af8b89fda255)

nor models

### Operating system

Fedora 40

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Just ran into the same thing in Bootc. Minor issue, the person who did #8093 😛 found it easier to move to Svelte 5 syntax, so this 'broke' when we both moved up to a recent UI package. Just change `on:close` and `on:breadcrumbClick` to `onclose` and `onbreadcrumbClick`.
