### ISSUE TITLE
GPU usage on Podman Desktop AI lab service screen

### ISSUE THREAD

**Issue by rrbanda** [containers/podman-desktop-extension-ai-lab#1499]
### Is your feature request related to a problem? Please describe

Unable to see GPU usage while running inference request

### Describe the solution you'd like

Next to vcpu usage as per screenshot, is it possible to have a GPU usage as well ? 
<img width="1511" alt="Screenshot 2024-08-06 at 8 45 07 PM" src="https://github.com/user-attachments/assets/c418873d-f2b5-492c-ae2d-6d9ff160cb7a">

**Comment by axel7083** [comment]
This feature cannot be added easily, as having access to this information is independent from podman.

Depending on the type of GPU you are using the usage cannot be collected with the same method, E.g. with an NVIDIA GPU you could see the usage with `nvidia-smi`, however this does not allow you to distinguish per process usage. 

When podman mount a device, it cannot control what the usage of this device is, it just let the process inside the container use it. For this reason, it would not be possible to monitor this metrics
