### ISSUE TITLE
feature(InferenceManager): support specific connection given a provider

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1529]
### Is your enhancement related to a problem? Please describe

Currently the InferenceManager support a provider id as argument, however we may have multiple connection per provider. 

https://github.com/containers/podman-desktop-extension-ai-lab/blob/d2f06e9bc6bf5274dde79e186e38bffd543a4b55/packages/shared/src/models/InferenceServerConfig.ts#L27-L30

### Describe the solution you'd like

Work is related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/1462

**Comment by jeffmaury** [comment]
Not sure it should be attached here as connection may be selected based on the model requirements
