### ISSUE TITLE
Need docs on windows GPU support

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#1538]
### Is your enhancement related to a problem? Please describe

Does it "just work" when running with WSL Windows? I thought you have to install nvidia container toolkit? That not the case anymore?

Just trying to figure out: https://github.com/containers/podman-desktop-extension-ai-lab/pull/1280

### Describe the solution you'd like

GPU documentation for how to setup with Windows WSL

**Comment by rfrht** [comment]
Hi @cdrage 
Wondering if https://podman-desktop.io/docs/podman/gpu addresses your need.

**Comment by cdrage** [comment]
> Hi @cdrage Wondering if https://podman-desktop.io/docs/podman/gpu addresses your need.

Haha! Good suggestion. I wrote that :) 

Thank you for reminding me about this issue, you are 100% right, with https://podman-desktop.io/docs/podman/gpu this can be closed now.
