### ISSUE TITLE
Adjust Inference Server details page UX

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1592]
### Is your enhancement related to a problem? Please describe

While the inference server page is listing the information, those are not easy to decipher. And we would like to introduce more sections later on.

<img width="1379" alt="Screenshot 2024-08-25 at 15 23 59" src="https://github.com/user-attachments/assets/417d78d0-b3e4-4f92-9bbf-5c301482114f">

### Describe the solution you'd like

We would like the screen to be better guiding the developer onto the different component and information displayed.

- "Server" should be rename "Inference Server"
- The most important information is the "Inference Endpoint" but it is buried into the screen, hard to find the first time you use the tool. It should be first. We would like to put more emphasis on this one. Also, we would like to have a label "Inference Endpoint:" and it should be obvious that the user can easily copy it (maybe displaying the copy icon). Wondering, if we should not use a different color for that one.
- Similarily, the documentation for the swagger UI is hard to spot the first time and people may even not notice it. We should have a label "Inference API documentations"
- Finally, along with https://github.com/containers/podman-desktop-extension-ai-lab/issues/495, we could put the "GPU Inference" onto a dedicated section.

**Comment by axel7083** [comment]
cc @ekidneyrh @MariaLeonova

**Comment by MariaLeonova** [comment]
@axel7083 how much UX support is needed? Shall I create a penpot mockup for this screen enhancements?

**Comment by axel7083** [comment]
> @axel7083 how much UX support is needed? Shall I create a penpot mockup for this screen enhancements?

I think yes that would help, as Stevan is talking about including some metrics in the page which would be a lot of changes https://github.com/containers/podman-desktop-extension-ai-lab/issues/495 and would probably need some discussion as this is currently something we do in podman-destkop (we uses the donuts for resources)
