### ISSUE TITLE
Create a form to start a new InstructLab session

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1617]
Only the UI workflow should be implemented as we are investigating the images

**Comment by axel7083** [comment]
Here is my first draft implentation for the `StartInstructLabSession` page.

![image](https://github.com/user-attachments/assets/40c310bf-f1ce-4f92-ba26-55d7802a00fb)

![image](https://github.com/user-attachments/assets/51201dc6-3e33-4e3e-b342-16a666e52f97)

## Mock-ups vs Implementation

![image](https://github.com/user-attachments/assets/641055c6-06fc-41a7-9601-1736f290177a)

Above is the mock-ups available [on penpot](https://design.penpot.app/#/workspace/97b0253e-42f9-817e-8004-e3d617836067/6e12068a-09a0-801a-8004-24b355541870?page-id=f03273e9-8179-80f3-8004-e7f92eac3e77).

1. Why are we using dropdowns for sections ? This is not something we are doing anywhere in podman-desktop. 
2. Why the session name is the last field ? This feel a bit weird to give a name at the end
3. Model selection do not match design of `StartRecipe` and `CreateService`.

The inspiration for `(+) Adding knowledge` and `(+) Adding skills` are from the `Container Import` page

![image](https://github.com/user-attachments/assets/0d3995d1-1cbb-4948-b8f2-0f3dab8cc0eb)

## Going deeper

I was curious to see how we could give more information about each section, and redirect user to the Instructlab repository to learn more on what is a skill and what is a knowledge, but not sure.

![image](https://github.com/user-attachments/assets/0f534ac0-23e6-4dcc-a467-e4e9bff2b8da)

I tried adding `(?)` next to the form labels, but I feel like the link color get redundant and weird on the eyes.

## Form validation

To make the `submit` button valid, I used the following 

https://github.com/containers/podman-desktop-extension-ai-lab/blob/2a1f82e5dd93c5f08894e1650cea7ae4f97dba42/packages/frontend/src/pages/StartInstructLabSession.svelte#L22

This mean either a skills or a knowledge is necessary (a combination is possible but at least one of them is required)

## Current branch

I am working on https://github.com/axel7083/ai-studio/tree/feat/start-instructlab-session if people want to experiment with the form.

cc @slemeur @jeffmaury

**Comment by slemeur** [comment]
cc @MariaLeonova

**Comment by MariaLeonova** [comment]
@axel7083 seems like we're working in parallel on some of the UI changes and will need to sync going forward. 

Firstly, please take a look at these enhancement suggestions that I have logged for InstructLab integration:

- https://github.com/containers/podman-desktop-extension-ai-lab/issues/1671 - is about spelling fine-tuning in the same way everywhere in the UI
- https://github.com/containers/podman-desktop-extension-ai-lab/issues/1670 - is about the fine-tuning icon consistency in the UI
- https://github.com/containers/podman-desktop-extension-ai-lab/issues/1716 - is for an extra button added on top to guide users to the InstructLab submissions
- https://github.com/containers/podman-desktop-extension-ai-lab/issues/1788 - is for adding helper text for Knowledge and Skills fields.

Secondly, there's some further work planned for IL mockups, that will be tracked in this epic: https://github.com/containers/podman-desktop-extension-ai-lab/issues/1743

As for the screens you're suggesting in this issue, I think the best way to go would be to have an in-person chat and go through all the questions.

For instance, #1788 is addressing your point on providing people with extra guidance.

**Comment by axel7083** [comment]
> As for the screens you're suggesting in this issue, I think the best way to go would be to have an in-person chat and go through all the questions.

Yeah! Thanks for the precisions, I also think that's the best way to do !

**Comment by MariaLeonova** [comment]
As per discussion, here's the latest proposal: 
![New IL Session Form](https://github.com/user-attachments/assets/478354ca-73dc-4ec8-aa40-525d18c51bc2)

**Comment by axel7083** [comment]
@MariaLeonova in our discussion you mention that we cannot define Knowledge and skills at the same time, how do this would be visible in your implementation ?

## Model Selection

![image](https://github.com/user-attachments/assets/c6b87e70-55dc-4dc1-9e44-98729756ad40)

We do not have specific icon for each models. 

## Dropdowns

![image](https://github.com/user-attachments/assets/4deaf73d-0dd5-40bb-bbf0-1adeb7acbb8c)

I still have some doubt with this dropdown system, we seems to only be able to select one file in your mock-up, so why do we need this dropdown ? 

## Form Style

in other AI Lab forms we put all the form items (Model Selection, number/string input) in a card, should we do the same for this form?

![image](https://github.com/user-attachments/assets/49636ed0-6999-408b-b2c9-654a4d96745f)

**Comment by MariaLeonova** [comment]
@axel7083 In the future users might be able to add both skills and knowledge, I suppose, so the UI will need to allow for that. Generally, for this type of either or situation, I'd suggest radio buttons. Or, in this case, it could be that skills field is disabled if knowledge is selected and vice versa. I'd be curious to see if there are existing similar patterns in Podman Desktop.
@ekidneyrh might have suggestions? 

Then, we could get rid of dropdowns and put the whole fine-tuning section on one card, as you are suggesting.

**Comment by MariaLeonova** [comment]
Here's a suggestion with radio buttons: 

![New IL Session Form- 2](https://github.com/user-attachments/assets/17b43b19-79bb-41ce-b916-fb48b8b43eee)

**Comment by MariaLeonova** [comment]
I made some changes as per discussion in the UX sync call discussion:

![New IL Session Form- 2 (1)](https://github.com/user-attachments/assets/91dd53f4-423a-41f7-be61-0d7fa16e6a86)

**Comment by axel7083** [comment]
To continue of the discussion, I don't think we need the big folder button => we are selecting a file anyway.

But from the Import Containers page in Podman Destkop we have the following

![Image](https://github.com/user-attachments/assets/dd2e0c3f-a299-4559-8088-47369c5425e1)

![Image](https://github.com/user-attachments/assets/0317b995-1aab-4ecf-b0a6-a2f758c3cf75)
 
I also think the `(+) Add another X` should be gray if the checkbox is not selected for the item

**Comment by MariaLeonova** [comment]
@axel7083 I got the folder pattern from Containers page - seems like both patterns co-exist currently in the UI: 
![Screenshot 2024-10-04 at 10 32 48](https://github.com/user-attachments/assets/34a91f8f-929c-4746-ab61-179c73644af1)


> I also think the (+) Add another X should be gray if the checkbox is not selected for the item


Can totally be, I agree!

**Comment by jeffmaury** [comment]
Why are we adding a constraint (skills or knowledge) when InstructLab is handling them the same ?

**Comment by jeffmaury** [comment]
> > Why are we adding a constraint (skills or knowledge) when InstructLab is handling them the same ?
> 
> I heard (not checked) that you cannot do both at the same time?

Needs to be verified because I was not aware
