### ISSUE TITLE
Model format typo on the model import page in Podman Desktop AI Lab Extension

### ISSUE THREAD

**Issue by Mohit-Gaur** [containers/podman-desktop-extension-ai-lab#1634]
### Bug description

The model import page in the AI lab extensions shows that the supported formats for mode files are .guff or .bin.
I think that .guff is a typo and it should display the correct format aka .gguf

### Operating system

macOS Sonoma 14.6.1 (arm)

### Installation Method

from Podman-Desktop extension page

### Version

1.0.0

### Steps to reproduce

- Open the Podman Desktop application.
- Navigate to the AI Lab extension.
- Go to models catalog and navigate to the models import page
- Observe the supported format guidance says .guff instead of .gguf

### Additional context

<img width="1162" alt="Screenshot 2024-08-30 at 11 49 40 AM" src="https://github.com/user-attachments/assets/d02b4d1b-6278-4507-a377-e05a67784d30">

**Comment by Mohit-Gaur** [comment]
I am reporting this issue on v1.2.3 of the AI Lab extension

**Comment by jeffmaury** [comment]
Thanks for reporting @Mohit-Gaur 

Dare to provide a PR  ?

**Comment by Mohit-Gaur** [comment]
@jeffmaury I'd be happy to :)
