### ISSUE TITLE
Update AI Lab logo and icon with new version

### ISSUE THREAD

**Issue by MariaLeonova** [containers/podman-desktop-extension-ai-lab#1660]
### Is your enhancement related to a problem? Please describe

The Podman Desktop AI Lab logo has been slightly reworked in https://github.com/containers/podman-desktop-internal/issues/308 and needs to be updated in the app.

### Describe the solution you'd like

The files are stored here: https://github.com/containers/podman-desktop-internal/tree/main/ai-lab/logo/new%20logo

**The icon**
The icon appears on the Podman Desktop left-hand navigation. 
[Light scheme](https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-light-scheme.svg) | [dark scheme](https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-dark-scheme.svg)

![image](https://github.com/user-attachments/assets/1fdbf989-0223-400a-9746-b222a7d33d71)

**The logo**
I would also suggest updating the Brain icon on the top: 
![Screenshot 2024-09-04 at 14 16 28](https://github.com/user-attachments/assets/b3c37c0f-b31d-4092-891a-7aa089003773)

### Additional context

We can discuss other placements in the comments.

**Comment by MariaLeonova** [comment]
One more place to update the icon would be in the Extensions Catalog:
<img width="1225" alt="Screenshot 2024-09-05 at 16 27 37" src="https://github.com/user-attachments/assets/21e6d2a0-f3a1-48a2-a484-743b73176401">

**Comment by MariaLeonova** [comment]
One more place would be in the banner on https://podman-desktop.io/

**Comment by jeffmaury** [comment]
@MariaLeonova I tried to update the icon.png using ai-lab-icon-light-scheme.png but it's missing transparent background:

![image](https://github.com/user-attachments/assets/b38c546c-51e1-4d8e-aa4a-1fdf6326264b)

**Comment by MariaLeonova** [comment]
@jeffmaury I exported them again, with changed settings - does this work? 
![ai-lab-icon-light-scheme](https://github.com/user-attachments/assets/d3eaf1e0-d6b7-4e04-b29d-7590840f8187)
![ai-lab-icon-dark-scheme](https://github.com/user-attachments/assets/316830a5-723c-49eb-a5b3-1ab5185f47a7)

**Comment by MariaLeonova** [comment]
I also checked - these svg files have no background: 
https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-light-scheme.svg
https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-dark-scheme.svg
