### ISSUE TITLE
feat: allow to disable wsl upload through hidden configuration

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1661]
### Is your enhancement related to a problem? Please describe

In the e2e tests we often have a problem where uploading the model to the WSL leads to freeze. The source of the problem is unknown, and is blocking for QE.

The main lead are related to the WSL Upload code, which is using the podman cli (E.g. podman.exe) which freeze for unknown reasons.

### Describe the solution you'd like

As discussed with @jeffmaury and @ScrewTSW, we could add an hidden option in the configuration to disable the WSL Upload.

**Comment by axel7083** [comment]
@ScrewTSW do we want to close this one ? or are we still interested to have this option ?

**Comment by ScrewTSW** [comment]
> @ScrewTSW do we want to close this one ? or are we still interested to have this option ?

I'd say we are still interested in having the option.
