### ISSUE TITLE
Migrate the qenvs image to a migrated version of the image under redhat-developer

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-ai-lab#1663]
### Is your enhancement related to a problem? Please describe

Qenvs image that we use to crate a windows azure agents (`quay.io/rhqp/qenvs:v0.6.3`) in the windows e2e workflow was moved under official repository.

### Describe the solution you'd like

Switch the image and use the actual version. Same change was done in e2e repo: https://github.com/containers/podman-desktop-e2e/pull/212

**Comment by ScrewTSW** [comment]
AI LAb nightly windows https://github.com/containers/podman-desktop-extension-ai-lab/pull/1859
