### ISSUE TITLE
More enablement of GPU acceleration

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1689]
### Epic domain

Sub tasks:

- [x] #1591 
- [x] #1582

**Comment by axel7083** [comment]
Should we include https://github.com/containers/podman-desktop-extension-ai-lab/issues/1708 in it ?

**Comment by jeffmaury** [comment]
> Should we include #1708 in it ?

I would keep it apart as #1708 is improving the implementation and this one is more about leading users to GPU
