### ISSUE TITLE
Redesigned inference server details mockup

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1691]
### Is your enhancement related to a problem? Please describe

See 

### Describe the solution you'd like

A mockup for the redesigned UI

**Comment by MariaLeonova** [comment]
@jeffmaury @slemeur @axel7083 I have a couple questions to help me understand the issue better: 

1. is there any documentation for this UI and working with model services in AI Lab?
2.  how are these two different? Which is the Endpoint URL to be copied? ![Screenshot 2024-09-12 at 10 23 13](https://github.com/user-attachments/assets/c786f8a4-837b-43e6-be16-3bbb7ffc4b87)
3. what is the user's main goal on this page and what have they come to do? If it's the URL they want, what would they do with it next?
4. where is the Inference API documentation now?
  
I have highlighted the issues at hand on this screenshot, so I will address them when redesigning the UI:

![Screenshot 2024-09-12 at 10 26 19](https://github.com/user-attachments/assets/e104d7c3-ff0c-4c4f-9023-beec2323cc99)

**Comment by jeffmaury** [comment]
> @jeffmaury @slemeur @axel7083 I have a couple questions to help me understand the issue better:
> 
>     1. is there any documentation for this UI and working with model services in AI Lab?

No only the README from the repo: https://github.com/containers/podman-desktop-extension-ai-lab?tab=readme-ov-file#usage
> 
>     2. how are these two different? Which is the Endpoint URL to be copied? ![Screenshot 2024-09-12 at 10 23 13](https://private-user-images.githubusercontent.com/14108590/366785773-c786f8a4-837b-43e6-be16-3bbb7ffc4b87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzI3MzYsIm5iZiI6MTcyNjEzMjQzNiwicGF0aCI6Ii8xNDEwODU5MC8zNjY3ODU3NzMtYzc4NmY4YTQtODM3Yi00M2U2LWJlMTYtM2JiYjdmZmM0Yjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5MTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYmIxYzYxMzA0NTlhMzliNDZhOTA0YjRkMjdjMDkzNmMyNzFmMzk4MzM0N2I0ZmYzOGJkOWNiZDU2ZTk2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUrz4mX0NOnp99f7jW5Qz-4LO8RgmUR3xAAXaVs9qQI)
The first one is the URL to the OpenAPI spec for the inference server, the second one is the base URL to the OpenAI like API to be configured in applications
> 
>     3. what is the user's main goal on this page and what have they come to do? If it's the URL they want, what would they do with it next?
Integrate it into their applications thus the snippets
> 
>     4. where is the Inference API documentation now?
On the OpenAI website; https://platform.openai.com/docs/api-reference/chat
> 
> 
> I have highlighted the issues at hand on this screenshot, so I will address them when redesigning the UI:
> 
> ![Screenshot 2024-09-12 at 10 26 19](https://private-user-images.githubusercontent.com/14108590/366786948-e104d7c3-ff0c-4c4f-9023-beec2323cc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzI3MzYsIm5iZiI6MTcyNjEzMjQzNiwicGF0aCI6Ii8xNDEwODU5MC8zNjY3ODY5NDgtZTEwNGQ3YzMtZmYwYy00YzRmLTkwMjMtYmVlYzIzMjNjYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5MTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYTBiY2U5MmM0NTRmNjhlMDhhYzVjZjZlYmY0YzYyNTcxZDgzZTZhMTc0OGNmMzNlNjJjNGE3MjViNWFjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4GzEb2hcRWV5wLPz2-J7fM79UYNpcWIeXkuhDg57Hk)

**Comment by MariaLeonova** [comment]
I have taken the first stab at the UI - please review, I'm pretty sure I missed some things or potentially mislabeled:
<img width="1276" alt="Screenshot 2024-09-13 at 15 20 28" src="https://github.com/user-attachments/assets/4a6ec244-ad75-4a84-80db-f8dd70b66dbe">

**Comment by jeffmaury** [comment]
> I have taken the first stab at the UI - please review, I'm pretty sure I missed some things or potentially mislabeled: <img alt="Screenshot 2024-09-13 at 15 20 28" width="1276" src="https://private-user-images.githubusercontent.com/14108590/367310769-4a6ec244-ad75-4a84-80db-f8dd70b66dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTg4MjQsIm5iZiI6MTcyNjQ5ODUyNCwicGF0aCI6Ii8xNDEwODU5MC8zNjczMTA3NjktNGE2ZWMyNDQtYWQ3NS00YTg0LTgwZGItZjhkZDcwYjY2ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0NTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZmRjODI5ODJiOTViOWRlMDJiZmU3NTcxZjQ5ODE0NTAxNmE1MDMzYmM0YzY3NGI3ZTNiYjA3NGUyOGE1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fNWAAWXzh2YjZahnt5l9T_ZHkWa-V5lc3NUNqqsSE4g">
> 
> [penpot](https://design.penpot.app/#/workspace/97b0253e-42f9-817e-8004-e3d617836067/4eb1e939-618a-80e7-8004-f3496af6eede?page-id=32f8e0b0-faba-80e9-8004-f5d37efed730)

Models should be Model.
I don't understand the endpoint that is related to GPU inference. The label GPU inference seems a duplicate to the GPU inference block

**Comment by axel7083** [comment]
> ![image](https://github.com/user-attachments/assets/8c7aedc4-529c-41af-810f-42cf2f2eff15)

Having a dedicated section for GPU seems useless to me, has we cannot provide insight of the GPU usages. There are no difference in the API between a GPU accelerate container and a CPU. Only the speed.

We can measure the CPU a container is using, but not the GPU.

Therefore I don't see the point on having a GPU section. Moreover cannot estimate the VRAM usage of a model on the GPU, the RAM estimation is for the Memory (ram).

> ![image](https://github.com/user-attachments/assets/39abc6b6-f023-4502-af3e-d7491069ea2b)

For the model, the name can be clickable to redirect to the model page, but having the `cpu` or `gpu` inference is not related to the model but to the hardware, all models can run on GPU if you have the right hardware (E.g. a nice Nvidia Card).

**Comment by MariaLeonova** [comment]
Thank you for the feedback! The ask to have GPU in a separate section comes form the original ticket: `Finally, along with https://github.com/containers/podman-desktop-extension-ai-lab/issues/495, we could put the "GPU Inference" onto a dedicated section.`

However, if it's not needed, it doesn't have to be. I'll update the mock.

**Comment by MariaLeonova** [comment]
@axel7083 @jeffmaury please review: 

![Server Details - 17 _ 9](https://github.com/user-attachments/assets/45e88445-c748-449a-be16-138f54257930)

**Comment by jeffmaury** [comment]
> @axel7083 @jeffmaury please review:
> 
> ![Server Details - 17 _ 9](https://private-user-images.githubusercontent.com/14108590/368045449-45e88445-c748-449a-be16-138f54257930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTcxMTAsIm5iZiI6MTcyNjU1NjgxMCwicGF0aCI6Ii8xNDEwODU5MC8zNjgwNDU0NDktNDVlODg0NDUtYzc0OC00NDlhLWJlMTYtMTM4ZjU0MjU3OTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3MDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OGM2NTk1Y2ZhOTk4MWEyNTQ4MzZlMDUzYjMzZTk0NmQ0YmE3MWZjNTkxZTIxMjQ3OWQ5ZTJmY2M5MTQ2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d7S562KkNVXotvFMA3Pv_4AHzpymdq-yDqiojk5-zes)

Not sure what is the second URL ?

**Comment by MariaLeonova** [comment]
@jeffmaury I just copied whatever is in the UI right now - do you feel like something shouldn't be there? Attaching a screenshot:
![Screenshot 2024-09-17 at 9 14 39](https://github.com/user-attachments/assets/22d9e846-4df3-4f12-8193-8eedbf4aca92)

**Comment by axel7083** [comment]
# Urls

There are two urls for the inference server (llama-cpp-python)

## `http://localhost:<port>/v1` 

The is the api link: we want user to copy it and use it for programmatic call

It is the link used in the code snippets

## `http://localhost:<port>/docs`

This is specific for llama-cpp-python inference server.

This is a link for the api documentation. This should be clickable, as user can click on it to open the browser navigate the documentation.

⚠️ This is not a link that would be here for every inference server (E.g. whisper-cpp do not have documentation link) 

# Order

We seems to be moving the Inference Card above the container, I have mixte feeling about it, as believe to keep the consistency between the screens of podman-desktop and AI Lab, we should keep it in the header.

I understand the inference details are important, but we are still a container, and this information should be at the top (IMO)

**Comment by jeffmaury** [comment]
> @axel7083 that's a great explanation, thank you! Is there a reason why `http://localhost:<port>/docs` is shown in a way that it's shown? Would it be okay if it looked like a regular link? Is `swagger documentation` a term generally familiar to developers?
> <img alt="Screenshot 2024-09-17 at 14 19 21" width="208" src="https://private-user-images.githubusercontent.com/14108590/368160726-f5a55f59-1b6b-4abd-b034-6a5a5e974ffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Nzk3NjUsIm5iZiI6MTcyNjU3OTQ2NSwicGF0aCI6Ii8xNDEwODU5MC8zNjgxNjA3MjYtZjVhNTVmNTktMWI2Yi00YWJkLWIwMzQtNmE1YTVlOTc0ZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEzMjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjhmYmMxNjI1Y2U5ZjU5ZGI0NDljOGMwNTcwMGY3M2YyNTBkOGVhMzE0NzUwNDU4NDYxZTcwN2E1MTI5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ee9j1PvkTkkxOgFFBkafF5gSZzbGZ59zB8XYin3sIX8">
> 
> @jeffmaury would this ^^ be different, local documentation link from the open API documentation https://platform.openai.com/docs/api-reference/chat then? And it is the openAI link that is missing now?

I think it should be OpenAPI rather that swagger

**Comment by axel7083** [comment]
I don't think we want to link the openai documentation website

**Comment by MariaLeonova** [comment]
> I don't think we want to link the openai documentation website

Why not? 
What would be the advantages / disadvantages of one over the other? Or maybe let's pose the question this way: what is it that the users will gain from documentation on this page? 

I would suppose they would learn more about Inference endpoints and how to use them in their apps. A good example here would be what Hugging Face do on their server pages - out of all the model catalogs and registries that UX has evaluated, they provide the most structured, relevant and helpful information. 

![image](https://github.com/user-attachments/assets/ff4933e9-9bd6-438b-913d-35a606e4527e)

**Comment by axel7083** [comment]
> ![image](https://private-user-images.githubusercontent.com/14108590/368471807-ff4933e9-9bd6-438b-913d-35a606e4527e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDY0NzUsIm5iZiI6MTcyNjY0NjE3NSwicGF0aCI6Ii8xNDEwODU5MC8zNjg0NzE4MDctZmY0OTMzZTktOWJkNi00MzhiLTkxM2QtMzVhNjA2ZTQ1MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmU5ZjRiOGZiMzlmNmNhMGQ3YTg5ZDA1Y2ZjZjVmM2RkMGM5YzQyMDMzZDQ0NzE5NzBkNjRkMTlhNWUwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEDLAqDs3mtax5VdV7QhmhXjziMbVJPp3pUCVfiPoXk)

I really like how they display the information;

Let's take a look at the tabs

### `Logs`

I have some doubt for the logs tab, which could be feasible to have, but we have the logs in the container details, which could be visible by clicking on 
![Screenshot from 2024-09-18 10-00-50](https://github.com/user-attachments/assets/ac162d66-d065-424a-a9da-aa6d2ef35ed5)

### Analysis` 

The analysis would not have much sense as we do not have much to put in, we could instead have a `Performance` tab, where we could display the memory/cpu utilisation. 

### `Settings`

We do not support changing the configuration after we started a container (sadly), but we could (maybe) have a readonly page)

**Comment by MariaLeonova** [comment]
> > ![image](https://private-user-images.githubusercontent.com/14108590/368471807-ff4933e9-9bd6-438b-913d-35a606e4527e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDY0NzUsIm5iZiI6MTcyNjY0NjE3NSwicGF0aCI6Ii8xNDEwODU5MC8zNjg0NzE4MDctZmY0OTMzZTktOWJkNi00MzhiLTkxM2QtMzVhNjA2ZTQ1MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmU5ZjRiOGZiMzlmNmNhMGQ3YTg5ZDA1Y2ZjZjVmM2RkMGM5YzQyMDMzZDQ0NzE5NzBkNjRkMTlhNWUwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEDLAqDs3mtax5VdV7QhmhXjziMbVJPp3pUCVfiPoXk)
> 
> I really like how they display the information;
> 
> Let's take a look at the tabs
> 
> ### `Logs`
> I have some doubt for the logs tab, which could be feasible to have, but we have the logs in the container details, which could be visible by clicking on ![Screenshot from 2024-09-18 10-00-50](https://private-user-images.githubusercontent.com/42176370/368474897-ac162d66-d065-424a-a9da-aa6d2ef35ed5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDY5NzcsIm5iZiI6MTcyNjY0NjY3NywicGF0aCI6Ii80MjE3NjM3MC8zNjg0NzQ4OTctYWMxNjJkNjYtZDA2NS00MjRhLWE5ZGEtYWE2ZDJlZjM1ZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMjY5MTVmMTRmYzhkZWNiZDg4ZTNmYTAyNWIxM2JjMDYxY2ZlZWMxOWNlZWFhODJmYjkyYTdlY2QzMTRiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6sUn90_zN_PsRVsyUXs37bcFKAiS9kI7y8bEUa56YU)
> 
> ### `Analysis`
> The analysis would not have much sense as we do not have much to put in, we could instead have a `Performance` tab, where we could display the memory/cpu utilisation.
> 
> ### `Settings`
> We do not support changing the configuration after we started a container (sadly), but we could (maybe) have a readonly page)

Yes, I am not saying we should copy them, tabs included,  I was merely showing the way they treat Endpoint URL there for some inspo^^

**Comment by axel7083** [comment]
I like the tabs, I would not mind having them

**Comment by MariaLeonova** [comment]
@ekidneyrh and I looked at the UI and we came up with another UI suggestion: 
![Screenshot 2024-09-18 at 12 12 54](https://github.com/user-attachments/assets/2b278408-fdc5-4029-bf94-feda688aaf89)

Here:
- the endpoint URL is front and center.
- documentation link looks like a link that can be clicked and is a different UI element from the URL, that one can copy and GPU inference label, which offers no action.
- more info link can go to the actual documentation on how to use the URL and swagger docs etc, if we choose to have it

**Comment by axel7083** [comment]
Why are we moving out the Container section of the header, I don't see the point

![image](https://github.com/user-attachments/assets/58ea1e97-3d51-4145-99e2-83e5d07bd679)

Having it at the top makes it consistent with other part of the application

![image](https://github.com/user-attachments/assets/720b073c-c177-4014-b948-7de383e7b605)

![image](https://github.com/user-attachments/assets/1aa75263-76c0-49a5-a935-1821b39d43da)

![image](https://github.com/user-attachments/assets/0470d993-ab0e-46d7-b6e3-f21fa648465c)

**Comment by MariaLeonova** [comment]
> Why are we moving out the Container section of the header, I don't see the point

It was not a decision that I made, it was just an artefact of the penpot file I was reusing from previous designs, I'll update it to match the current state.

**Comment by MariaLeonova** [comment]
![Screenshot 2024-09-18 at 15 36 08](https://github.com/user-attachments/assets/49ae6645-9821-4bb7-8c00-1641c1f195f9)
 @axel7083 ^^

**Comment by axel7083** [comment]
> @axel7083 ^^

Great !

**Comment by jeffmaury** [comment]
LGTM but I think the Inference Server block takes to much space vertically. Is there a way to shrink it a little bit ? What is the More Info link ?

**Comment by slemeur** [comment]
The most important information on this page is the endpoint information: that needs to be moved at the top. There is no reason a user would start an inference server otherwise. 

On the UI, we have boxes, into boxes, into another set of boxes. Would it be possible to make things a bit simpler? 

There are a couple of inconsistencies:
- "Inference Server" is a section with an header, but the model is a section without an header and then "Client Code" is an header again. Maybe a "Model Info" section where we could be displaying a bit more information (size on disk, file name, file path, quantization used)
- The value should be next to its title/description of the field, otherwise we create dozen of lines and are not efficiently using the space. And I would add, that in the future we could be adding more information

**Comment by MariaLeonova** [comment]
@slemeur I tried to address most of your concerns in this new mock: 
- fewer boxes: one big background for all the top part and two smaller grey boxes to highlight the endpoint URL and the name
- added some model details
- link next to the endpoint URL can lead to swagger documentation
- More info link, I was hoping, could point to some documentation on how to use the endpoint URL and where to put it etc

Here's the penpot link for comments: [penpot](https://design.penpot.app/#/workspace/97b0253e-42f9-817e-8004-e3d617836067/4eb1e939-618a-80e7-8004-f3496af6eede?page-id=32f8e0b0-faba-80e9-8004-f5d37efed730&layout=layers )
  
I would also be happy to meet and talk through individual elements.
  
![Copy - Server Details - 2 _ 10 (1)](https://github.com/user-attachments/assets/43c16edc-27a0-45eb-b453-412a15bb0034)

**Comment by MariaLeonova** [comment]
Couple comments from UX sync call: model name should be clickable; quantisation info is currently not available.

**Comment by axel7083** [comment]
> Couple comments from UX sync call: model name should be clickable; quantisation info is currently not available.

Breadcrumbs missing, but nice mock-ups, love it !

**Comment by nichjones1** [comment]
Closed,  implementation is being track by #1592
