### ISSUE TITLE
Import model

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#173]
A user should be able to import a model into the model registry

**Comment by vrothberg** [comment]
How does the workflow look like?  Will there be an import button on the models page?

**Comment by jeffmaury** [comment]
> How does the workflow look like? Will there be an import button on the models page?

I'm not sure we have a mock up for it but that's the idea

**Comment by lstocchi** [comment]
What do we mean by importing? Can i download any model from huggingface (or anywhere else) and import it into desktop or i have the model (one present in the catalog, like mistral) in another location of my pc and i want desktop to find it?

**Comment by lstocchi** [comment]
@slemeur have answered it during the call. So i can download a model from huggingface and import it

**Comment by slemeur** [comment]
Correct, consider that the "import model" will be allowing a user to load a local model file and start the model serving with that model file.

**Comment by lstocchi** [comment]
@slemeur you mean just by clicking on import, it start the model serving? So it is just one shot? 

I mean if i close ai lab and open it the day after, do i see the imported model in the model list or i need to execute import again?

**Comment by slemeur** [comment]
We should see that as extending the catalog of model. 
- So on the list of models, we would have a button "Import".
- User will be able to select the model from the local disk
- Once imported, the model is indicated with the list as a "user's model"
- Then, the user is able to start a model serving from that model, or start a playground for it
