### ISSUE TITLE
Environment implementation

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#177]
Tasks:

- [x] #178
- [x] #179
- [x] #180
- [x] #181
- [x] #162
- [x] #295
- [x] #286
- [x] #292
- [x] #285
- [x] #270
- [x] #328
- [x] #293
- [x] #235
- [x] #61
- [x] #265
- [x] #281
- [x] #284

**Comment by slemeur** [comment]
Closing, all tasks completed
