### ISSUE TITLE
Stopping inference server does not remove server from the services list

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1822]
### Bug description

If you stop the container for the inference server, it is not removed from the Services list

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by axel7083** [comment]
I do not reproduce

https://github.com/user-attachments/assets/c300cb7d-f21b-4385-8f66-88e8c2450d6d

**Comment by jeffmaury** [comment]
Cannot reproduce anymore. Was probably missing a build phase
