### ISSUE TITLE
Visual glitch with recipe catalog

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1833]
### Bug description

![image](https://github.com/user-attachments/assets/7bc30496-01d1-4477-9f6e-a175fedeb0f5)

### Operating system

Fedora 40

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Small screen

**Comment by gastoner** [comment]
![Image](https://github.com/user-attachments/assets/e8c4ac0b-6832-4979-b042-d5f160d709a7)

Looks like already been fixed

**Comment by slemeur** [comment]
@gastoner if you use a snapshot of ai-lab, you'll still see the issue.

**Comment by axel7083** [comment]
@gastoner you can inspect and replace `v1.3.0` by a very very long string, you will see that the `More details` come out of the card
