### ISSUE TITLE
Recipe ref is displayed out of the card

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#1868]
### Is your enhancement related to a problem? Please describe

When a recipe uses a commit ID as a ref of a repository, the ID overflows of the Recipe card
![Image](https://github.com/user-attachments/assets/0e955a4a-da27-4450-b490-738e91db7499)

### Describe the solution you'd like

Hide the part of ref that overflows (add a tooltip?)

**Comment by jeffmaury** [comment]
Duplicates of #1833
