### ISSUE TITLE
Cannot pull the recipe and copy the model onto the podman machine with hyperv virtualization provider

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-ai-lab#1885]
### Bug description

I am getting error for pulling a summarizer recipe and uploading the model when on podman machine with hyper V provider on windows. 

Errors say:
```
Something went wrong while pulling Summarizer: Error: (HTTP code 500) server error - container create: statfs /C:\Users\Ondrej\.local\share\containers\podman-desktop\extensions-storage\redhat.ai-lab\models\hf.instructlab.granite-7b-lab-GGUF: no such file or directory

Something went wrong while starting the inference server: Error: (HTTP code 500) server error - container create: statfs /C:\Users\Ondrej\.local\share\containers\podman-desktop\extensions-storage\redhat.ai-lab\models\hf.instructlab.granite-7b-lab-GGUF: no such file or directory
```

![Image](https://github.com/user-attachments/assets/847e7e55-6dd6-4f3d-ab65-aab607e6b52d)

### Operating system

windows 10

### Installation Method

from Podman-Desktop extension page

### Version

next (development version)

### Steps to reproduce

1. Podman Desktop 1.13.2
2. AI-lab from Catalog 1.2.3
3. Podman Machine (12 GB memory, 5 CPUs) with hyperv
4. Start summarizer recire
5. Assert: Project is running
Actual result: Errors pulling a project and copying the model

### Relevant log output

main ↪️ [ai-lab] Something went wrong while trying to stat remote model path Error: Command execution failed with exit code 1
    at ChildProcess.<anonymous> (C:\Users\Ondrej\AppData\Local\Temp\2nELiQSbfBJmGdVdMl3N7AC2Ovh\resources\app.asar\packages\main\dist\index.cjs:342:13022)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

update images Error: connect ENOENT \\.\pipe\podman-machine-default
(anonymous) @ event-store.ts:237
Promise.catch
(anonymous) @ event-store.ts:236
setTimeout
o @ event-store.ts:228
await in o
(anonymous) @ event-store.ts:262
emit @ VM4 sandbox_bundle:2
send @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2

**Comment by jeffmaury** [comment]
Copying model file should be limited to WSL
