### ISSUE TITLE
Overflow in Recipes catalog

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-ai-lab#1924]
### Bug description

The version needs an ellipsis to avoid overflowing:

![Image](https://github.com/user-attachments/assets/09ee6756-8a1c-4ab0-915c-19cc9e33b24e)

### Operating system

macOS 15.0

### Installation Method

None

### Version

next (development version)

**Comment by jeffmaury** [comment]
Duplicates #1833
