### ISSUE TITLE
Use  functionary model for function calling

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#1961]
### Is your enhancement related to a problem? Please describe

When using the model `MaziyarPanahi/Mistral-7B-Instruct-v0.3.Q4_K_M`, the following request does not return a correct response:

(the assistant asks to call the function motherName('Pierre'), which returns 'Marie', but the model is not able to know who is Pierre's mother)

(actually, it returns the correct response the first time the request is done, but returns a wrong response for the following requests)

```
curl --location 'http://localhost:8000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
  "messages": [ {
    "role" : "system",
    "content" : "You are an helpful assistant"
  }, {
    "role" : "user",
    "content" : "Who is the mother of Pierre?"
  }, {
    "role" : "assistant", "content": null,
    "tool_calls" : [ {
      "id" : "call__0_motherName_cmpl-ac3d3307-c68c-4814-8ab7-8e3851f837a3",
      "type" : "function",
      "function" : {
        "name" : "motherName",
        "arguments" : "{\"arg0\": \"Pierre\"}"
      }
    } ]
  }, {
    "role" : "tool",
    "tool_call_id" : "call__0_motherName_cmpl-ac3d3307-c68c-4814-8ab7-8e3851f837a3",
    "content" : "Marie"
  } ]
}'
```

## Note on current function calling recipe

The function calling recipe currently in the catalog stops at the first assistant response (saying which tool to call with which argument). But instead of sending back the response of the tool to the model (along with the history of messages), the app directly displays the result of the call.

More complete examples (like the one at https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/Functions.ipynb) send back the result to the model to get another response. This is what is illustrated in this issue with the `curl` request.

### Describe the solution you'd like

By using a model `functionary` as recommended by llama-cpp-python documentation (https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/Functions.ipynb), the model replies correctly.

**Comment by slemeur** [comment]
Shouldn't it this be a bug?

**Comment by axel7083** [comment]
> By using a model functionary as recommended by llama-cpp-python documentation

This documentation in llama-cpp-python is outdated. And only cover very old version of functionary (v2.2) currently functionary are at `v3.2`, llama-cpp-python **do not** support version `v2.4`, ` v2.5` `v3.0`, `3.1`, `3.2`.  

I've already covered the relationship between the functionary team and llama-cpp-python in https://github.com/containers/podman-desktop-internal/issues/324 

Even tho I would like to support functionary, we could only support a version old version, therefore we would not be able to sopport any newer, as the llama-cpp-python team do not interested in supporting it.

**Comment by axel7083** [comment]
Closing as cannot be implemented with any other model that a very old one (technical reasons), if this is something that we decide, could be re-open.
