### ISSUE TITLE
Move the AI Lab listening port in its own configuration page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1978]
### Is your enhancement related to a problem? Please describe

![Image](https://github.com/user-attachments/assets/d7b4db5c-d05a-4c2b-a481-17c6f036b3d8)

Today, when you are enabling AI Lab, it starts an Ollama compatible endpoint, so a user can programmatically interact with Podman AI Lab. 

The problem is this is not very discoverable and the configuration of the endpoint port feels disconnected as well.

### Describe the solution you'd like

**1 - Remove AI Lab port from the status bar**

**2 - Create a new page accessible from Podman AI Lab sidebar**
Name of the page: "AI Lab Service" 

In this page, we will provide the following explanation:
Integrate Podman AI Lab directly into your development workflows by using its REST API endpoints.  Compatible with Ollama's endpoints, you can seamlessly access and utilize the capabilities of Podman AI Lab without relying on its graphical interface

We will add a link to the APIs we are supporting.

Then, we should have a section with "Local Server" and a dedicated page "Server Settings".
The first item, will be the Port to listen on.

We should be keeping the possibility to change the Port in the settings of Podman AI Lab extension as well

**Comment by gastoner** [comment]
@slemeur 
I'll try to mimic the preferences design as is in PD to ai-lab 
![Image](https://github.com/user-attachments/assets/dab824d9-aff7-42af-945c-2e09de48a1b2) - There are missing collors + need to create inputs for numbers

Also in the nav on the left, I'm not sure with the title. Maybe something like configuration and below the AI Lab Service?
