### ISSUE TITLE
chore: update to @podman-desktop/ui-svelte 1.14

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1993]
### Is your enhancement related to a problem? Please describe

We are using version 1.12 

https://github.com/containers/podman-desktop-extension-ai-lab/blob/79d1543e3f7aaeed7871fa75bf50e25b99befc78/packages/frontend/package.json#L19

Newer version improve the components, however there are some issue with the dependabot because svelte check is failing.

### Describe the solution you'd like

Fix the svelte check errors

**Comment by benoitf** [comment]
blocked by https://github.com/containers/podman-desktop-extension-ai-lab/issues/1897

**Comment by axel7083** [comment]
> blocked by [#1897](https://github.com/containers/podman-desktop-extension-ai-lab/issues/1897)

Yes I opened https://github.com/containers/podman-desktop-extension-ai-lab/pull/1994
