### ISSUE TITLE
models path should not use url or at least sanitize it

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#205]
To make some tests, I created the following models

```
  {
      "id": "dummy-debug",
      "name": "dummy-debug",
      "description": "dummy-debug",
      "hw": "CPU",
      "registry": "dummy-debug",
      "popularity": 3,
      "license": "?",
      "url": "https://avatars.githubusercontent.com/u/42176370?v=4"
    },
```

When pulling application I am getting the following error

<img width="418" alt="image" src="https://github.com/projectatomic/ai-studio/assets/42176370/77038c9a-9522-409b-961b-79eac177d996">

**Comment by slemeur** [comment]
Closing as obsolete
