### ISSUE TITLE
Chat Bot AI app with lmstudio-community/granite-3.0 reiterates when input with response in the console output mutliple times

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-ai-lab#2065]
### Bug description

When sending an input into a prompt via browser, first input is processed correctly, but second question/input is kinda copied into answer prompt and seems like resend and appears iteratively in the output again and again. more questions make it worse.

Ref: https://github.com/containers/podman-desktop-extension-ai-lab/pull/2024

### Operating system

Mac OS 14

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Install 1.3.2 AI Lab
2. Create podman Machine (Mac OS libkrun)
3. Start up chat bot app with mentioned model
4. Assert: app is up and running
5. In the App's details -> open the browser
6. Send an input and check for the output
7. Repeat step 6. 
8. Assert: LLM model answers as expected
Actual result: app/model responses multiple times like it is recycling the input over and over

**Comment by jeffmaury** [comment]
Cannot reproduce on Win11Pro. Tested with the 2 following prompts:

1. What is Podman Desktop ?
2. How does it compare to Docker Desktop ?

Will test on MacOS/libkrun
