### ISSUE TITLE
Podman AI Lab 1.3.4

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#2119]
### Is your enhancement related to a problem? Please describe

Let's make a new bug fix release

### Describe the solution you'd like

Include new Quarkus recipe and latest version of the recipes (as 2 of them have been fixed

### Additional context

PRs to be included:
- [x] #2059
- [x] #2066
- [x] #2069
- [x] #2074
- [x] #2121
- [x] #2152
- [x] #2187

**Comment by slemeur** [comment]
Since all the sub-tasks are done - Can we do the release?
