### ISSUE TITLE
Recipe alignment can cause the details button to disappear

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop-extension-ai-lab#2216]
### Bug description

When one of the text elements is too long, the button disappears to the side

### Operating system

any

### Installation Method

from `ghcr.io/containers/podman-desktop-extension-ai-lab` container image

### Version

next (development version)

### Steps to reproduce

* Install AI Lab from 1.3.3 staging
* Open AI Lab Recipes

### Relevant log output

```shell

```

### Additional context

![Image](https://github.com/user-attachments/assets/4e221eb4-f250-4d25-9d19-a62d10a09d88)
![Image](https://github.com/user-attachments/assets/4c793a01-ce0f-4bf9-82ae-313ed26e0704)

**Comment by gastoner** [comment]
I think that this was solved in https://github.com/containers/podman-desktop-extension-ai-lab/pull/1996 
I think that `ghcr.io/containers/podman-desktop-extension-ai-lab` container image is missing the code that fixes this

Code that fixes this:
https://github.com/gastoner/podman-desktop-extension-ai-lab/blob/main/packages/frontend/src/lib/RecipeCard.svelte#L45
`flex-grow text-[var(--pd-content-card-text)] opacity-50 whitespace-nowrap overflow-x-hidden text-ellipsis`

In DevTools: 
![Image](https://github.com/user-attachments/assets/61a0191b-9510-4426-a073-b4c62040fe3b)

**Comment by ScrewTSW** [comment]
not present in 1.3.4, closing
