### ISSUE TITLE
Warn users if they are using a podman machine with few resources

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#227]
It may happen that users want to play with ai-studio but they have a machine with few resources.
We should show a warning somewhere to explain that having less than Y GB and X CPUs could make the recipe run extremely slow and it is recommended to create a new machine with more resources.

- [x] #873
- [x] #874

**Comment by axel7083** [comment]
From my understanding, we had a mockup for that @mairin 

And we do not need to create a new machine I think we can increase an existing with the following comment https://github.com/containers/podman/issues/12713#issuecomment-1371105116)
> I did not test it

**Comment by mairin** [comment]
Yep you are right @axel7083 here is the mockup:

![Recipe Catalog - Podman machine warning](https://github.com/projectatomic/ai-studio/assets/799683/a868639a-afde-43a0-b839-0320f1866a20)

**Comment by axel7083** [comment]
Now the issue, if that we don't know what to do when the user click on `Upgrade` as we do not have apis, nor ways to upgrade it on the extension side

We might want to redirect the user to the podman machine config ?

cc @benoitf maybe you have an opinion/pov ?

**Comment by jeffmaury** [comment]
Such a check should be present in various places of the AI Studio UI

**Comment by vrothberg** [comment]
I closed https://github.com/containers/podman-desktop-extension-ai-lab/issues/502 in favor of this issue but moved it over the 1.0 milestone.

**Comment by lstocchi** [comment]
Closing this as both issues have been completed
