### ISSUE TITLE
Detect when "AI App" is running, by checking containers healthchecks

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#265]

**Comment by axel7083** [comment]
Can we detect if the pod is stopped ?

https://github.com/projectatomic/ai-studio/assets/42176370/9c56056a-30fb-4180-bbea-75a3cd45be20

**Comment by feloy** [comment]
Yes, you are raising two problems. 

First is that in the Environments page, we are displaying 'running' when the pod is started, but not completely running. As discussed in another issue, we cannot receive events when the state of the pod changes, and so we cannot get (reactively) the currenty state of the pod. That means we need to do some pulling to get the information. This issue proposes to pull the status of the application port, instead of pulling the status, as the application port is more precisely what the user is waiting for.

The second is that the status in the Recipe page is not correctly updated when the pod changes (deleted, ...). We need to work on this too

**Comment by axel7083** [comment]
> Yes, you are raising two problems.
> 
> First is that in the Environments page, we are displaying 'running' when the pod is started, but not completely running. As discussed in another issue, we cannot receive events when the state of the pod changes, and so we cannot get (reactively) the current state of the pod. That means we need to do some pulling to get the information. This issue proposes to pull the status of the application port, instead of pulling the status of the pod, as the application port is more precisely what the user is waiting for.
> 
> The second is that the status in the Recipe page is not correctly updated when the pod changes (deleted, ...). We need to work on this too, using the `podmanConnection` class should help

Thanks for the details!

**Comment by feloy** [comment]
@ekidneyrh This change will add a new state to the pod ued to run an AI App. 

Before, the state of the pod were either running or not running.

With this change, a pod can be running but not healthy (for example, the model container is started, but is not ready to serve connections yet). The frontend will have a new variable `healthy`, and we will want to materialise this value in the frontend.

We currently display this state in 2 places: 
- in the ai apps list, in the Status column:
  - either with `AI App is running` when the app has been started in the current Podman Desktop/AI Lab session
  - or with `Pod running` when the app has been started in a previous session of Podman Desktop/Ai Lab
- in the recipe page, in the "AI Apps Details" region:
  - the running Status of the pod is displayed (can be either RUNNING, DEGRADED, etc)

**Comment by feloy** [comment]
fixed by #742
