### ISSUE TITLE
multi instance of an application

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#267]
What is the expected behaviour when multiple pods have the same value for `ai-studio-recipe-id`. We should handle the case where multiple instances of an application exist.

**Comment by feloy** [comment]
On an upcoming PR, I'm adding `ai-studio-model-id` label to the pod (to be able to restart it with the good model). It seems we will have to check the unicity of this pair (recipeId, modelId), to be sure the same application is not running several times with the same model

**Comment by lstocchi** [comment]
My understanding is that there should be just 1 pod per recipe/model. 
Let's say we have a pod `ai-studio-recipe-id=X` and `model=Y` which is in any state (running, stopped, whatever), when users go to the X recipe page and model selected is Y, they see this component (based on the pod status, they can start/stop/remove it)
![image](https://github.com/projectatomic/ai-studio/assets/49404737/96b4689e-8476-49b9-bfe7-45035083d5bb)

if a user swaps model to Z and there is no pod having `ai-studio-recipe-id=X` and `model=Z` we show the normal UI with the button `Run application`

**Comment by slemeur** [comment]
not relevant anymore
