### ISSUE TITLE
Application in "running" state seems to be still "loading"

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#272]
After starting the recipe's application, the user is landing into this stage:

<img width="1162" alt="Screenshot 2024-02-12 at 13 16 03" src="https://github.com/projectatomic/ai-studio/assets/1636769/1946fbc6-c0b5-4860-b061-efed570912da">

The loader in the "running" button is making the user feels it is still loading.

**Comment by lstocchi** [comment]
Closing as this is quite old, there is no running button now and the UI is clear
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/49404737/c528538e-deff-4c13-9f86-45409366f9fa)
