### ISSUE TITLE
SimpleGit calling cannot find the git command when Podman Desktop executed from flatpak

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#390]

**Comment by jeffmaury** [comment]
See https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-CUSTOM-BINARY.md

**Comment by benoitf** [comment]
I think removing the need of the git client would make it work everywhere as I suppose some people don't have the git utility

**Comment by feloy** [comment]
I'm looking at using isomorphic-git instead of simple-git. The isomorphic-git library has some differences which make the port not trivial (but still reasonably possible):

- the `ref` accepted by the `checkout` or `clone` methods does not recognize short commit ids, only long ids (https://github.com/isomorphic-git/isomorphic-git/issues/1180)
- there is no method to get the tracking branch (https://github.com/isomorphic-git/isomorphic-git/issues/233)
- there is no method to get the number of commits behind/ahead the tracking branch
