### ISSUE TITLE
discussion(playground): design and features

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#401]
## Playground design and features

The playground is the entry door to tests models. However as a developers, I might want to call the models directly to test it in my application. How do we empower the developers ?

## Providing generated code in several languages to call directly the API

This is tricky as we **do not** want to support a tool responsible of generating the code, we might want to use something that already exists.

We are using the [open**ia** npm package](https://www.npmjs.com/package/openai) to prompt the model server in our playground implementation today. 
> ⚠️ IMHO we should move away from this library as it is mainly made for calling Open**ia** apis, and I would rather avoid promoting their system when we try to provide local, and open source models.

A **nice** alternative is to use open**api** speicification. For example, the library mention above, is _mainly_ a client for the following swagger [github/openai/openai-openapi/openapi.yaml](https://github.com/openai/openai-openapi/blob/master/openapi.yaml).

We could instead of using this library, generate a client for the given methods our server support, and call them directly. Moreover, since this is an open well known format, we could even display it in the playground

**mockup playground with OpenAPI spec**

<img width="709" alt="image" src="https://github.com/projectatomic/ai-studio/assets/42176370/88bf5312-87c1-493e-828c-fb7ec5db34cf">

## Providing the curl command to replicates what happened in the playground

We should probably limit the _magic_ that the playground is doing, to make it easily reproducible with basic command by the user. If we execute only basic curl command, we could use then tools such as [curlconverter](https://www.npmjs.com/package/curlconverter) to provide code snippet for developers.

> ❓ I couldn't not find documentation, but if it is possible, we could also support "open in Postman". As a developers I like to reproduce easily in tool I am familiar with.

**Comment by MichaelClifford** [comment]
@axel7083 I like the idea of providing the user direct access to the model (and all its associated API's) from the playground.

The OpenAI OpenAPI might have endpoints that are not implemented by our server though. The current playground server exposes its API's at `http://0.0.0.0:8001/docs` and `http://0.0.0.0:8001/openapi.json`

<img width="1567" alt="Screenshot 2024-02-21 at 10 28 55 AM" src="https://github.com/projectatomic/ai-studio/assets/4494906/ff340517-1040-48f9-ba97-f5ee8efb6c6b">

**Comment by axel7083** [comment]
<img width="785" alt="image" src="https://github.com/projectatomic/ai-studio/assets/42176370/ef5d643b-36b7-4005-bd3e-15b10f959c3f">

I really like the `logs` section

**Comment by axel7083** [comment]
Closing as resolved by PlaygroundV2
