### ISSUE TITLE
Add documentation for adding items to the catalog

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#41]
The list of available items in the recipe catalog is provided from a JSON file.
We need a simple documentation for one external contributor to add one item to the catalog and explain what will be the process.

**Comment by slemeur** [comment]
duplicate by #19

**Comment by feloy** [comment]
Where do we want to display this documentation?

**Comment by slemeur** [comment]
Will be fixed by #123
