### ISSUE TITLE
Provide a way to cleanup recipes

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#469]
After I started all the samples, I'd like a way to clean them up.

**Comment by vrothberg** [comment]
I agree.

I can stop an app:
![Screenshot 2024-03-27 at 16 57 55](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/8c76d186-7ead-4825-91cd-7882a27ff1fa)

But then it's not displayed in the AI Apps page anymore:
![Screenshot 2024-03-27 at 17 21 50](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/43cd9dc8-f399-498b-809f-de10352f13b2)

When it runs, I can stop it in the AI Apps page, but cannot delete it:
![Screenshot 2024-03-27 at 17 22 10](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/30c9bdb8-4429-4c08-80c3-ae83833b8074)

I feel like besides the ability to delete the App, it would also make sense to display not-running/stopped AI Apps in the that page.

@slemeur @axel7083 @lstocchi what do you think?

**Comment by feloy** [comment]
> I agree.
> 
> I can stop an app: ![Screenshot 2024-03-27 at 16 57 55](https://private-user-images.githubusercontent.com/11679875/317352011-8c76d186-7ead-4825-91cd-7882a27ff1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTc4MjAsIm5iZiI6MTcxMTU1NzUyMCwicGF0aCI6Ii8xMTY3OTg3NS8zMTczNTIwMTEtOGM3NmQxODYtN2VhZC00ODI1LTkxY2QtNzg4MmEyN2ZmMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYzY2ZjEwYmZkZTQxMDBlZDQ0N2Q5ODFjMGY3ZWJiMTAzNDg3MjA4YTE3OWQ3ZmJhNTFmNDQ1MjAxMmYwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KN5zoEOhULgoOTja-fMGGMo9iaVayAD9Ob5sSl271lg)
> 
> But then it's not displayed in the AI Apps page anymore: ![Screenshot 2024-03-27 at 17 21 50](https://private-user-images.githubusercontent.com/11679875/317352142-43cd9dc8-f399-498b-809f-de10352f13b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTc4MjAsIm5iZiI6MTcxMTU1NzUyMCwicGF0aCI6Ii8xMTY3OTg3NS8zMTczNTIxNDItNDNjZDlkYzgtZjM5OS00OThiLTgwOWYtZGUxMDM1MmYxM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMDNmNjZlY2Q0ZmJkZWQ5NGNlNzhkMWM5NmQyNWY0OGRkZjcyNThjODk0MzQxNGFiZDEwMDkxNWZmZjAwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oki0J8U4qdLdh18sM5CKJt1FMZGIL9K8GZaz2qUiPIs)
> 
> When it runs, I can stop it in the AI Apps page, but cannot delete it: ![Screenshot 2024-03-27 at 17 22 10](https://private-user-images.githubusercontent.com/11679875/317352303-30c9bdb8-4429-4c08-80c3-ae83833b8074.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTc4MjAsIm5iZiI6MTcxMTU1NzUyMCwicGF0aCI6Ii8xMTY3OTg3NS8zMTczNTIzMDMtMzBjOWJkYjgtNDQyOS00YzA4LTgwYzMtYWU4MzgzM2I4MDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjYyNzcwZmE1NGZlZDE2MjA0YmYwYmZiYWRlZmUwY2EwYjIyYmNmMTJiOThmMzQ5NDgxNDU2ZmQwODc0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1pd_PnsZhhzTHeykNmp7Hmjil1BkjvxPwU21GD1nxo)
> 
> I feel like besides the ability to delete the App, it would also make sense to display not-running/stopped AI Apps in the that page.
> 
> @slemeur @axel7083 @lstocchi what do you think?

In fact, the Stop button has the effect to **delete** the pod, not stop it.

It has been discussed during an UX call, and we didn't want to have 2 buttons, one Stop button and one Delete button, to not confuse the user on which one to use, so it has been chosen to keep only the Deletion of the app (using a Stop button, which can be confusing, I would agree)

**Comment by feloy** [comment]
We wanted to hide the low-level and consider the app as either running or deleted. But it depends on if we really want to hide this low-level "complexity". It is not done for models services for example, so we could be consistent with it and have much more states for the app.

@slemeur WDYT?

**Comment by axel7083** [comment]
@slemeur introduced by https://github.com/containers/podman-desktop-extension-ai-lab/pull/719 we have the delete action on a recipe. Does this resolve this issue, or you add something else in mind ?

<img width="321" alt="image" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/62f8a45f-28f6-42a1-8fb8-44c02fb6ec97">
