### ISSUE TITLE
Provide a warning to users to get a large enough Podman Machine

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#502]
![image (1)](https://github.com/projectatomic/ai-studio/assets/1636769/9e1c9b96-2c73-4c4a-a71b-e2f4c92a6ded)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/projectatomic/ai-studio/issues/227

**Comment by vrothberg** [comment]
Closing in favor of https://github.com/containers/podman-desktop-extension-ai-lab/issues/227
