### ISSUE TITLE
missing pieces in recipe catalog

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#518]
The current recipe catalog shows a number of missing pieces (see below).  I am not sure what the current plans are.  Will the missing recipes be added?  It may be worth explaining users what a recipe is.

![image](https://github.com/projectatomic/ai-studio/assets/11679875/c8691336-34c5-4a63-87f4-a1960dd97450)

**Comment by jeffmaury** [comment]
Dup of #481

**Comment by vrothberg** [comment]
@jeffmaury will the missing pieces be added?  I'd prefer to not show so many empty categories as it looks incomplete.

**Comment by jeffmaury** [comment]
> @jeffmaury will the missing pieces be added? I'd prefer to not show so many empty categories as it looks incomplete.

We will remove empty categories anway

**Comment by vrothberg** [comment]
Awesome, thank you!
