### ISSUE TITLE
Add code gen specific models 

### ISSUE THREAD

**Issue by MichaelClifford** [containers/podman-desktop-extension-ai-lab#534]
We probably want to have models that have been fine tuned for code generation as part of the available models. Here two mistral variants I've tested.  

* https://huggingface.co/TheBloke/Mistral-7B-codealpaca-lora-GGUF (apache-2.0)
 * https://huggingface.co/TheBloke/Mistral-7B-Code-16K-qlora-GGUF ((apache-2.0)

**Comment by lstocchi** [comment]
@slemeur should we add them to https://docs.google.com/document/d/1aYQoLVAxnG_4dDe3C0d26IYHr7z_H-r6Vtvn8yZ3AxQ/edit#heading=h.hm8uxrlx2crs and wait for a legal confirmation before to add them into the catalog?

**Comment by lstocchi** [comment]
related to #483
