### ISSUE TITLE
Add breadcrumbs for consistent navigation patterns

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#551]
In Podman Desktop, when you have a list and get into the details of one of its item, you get a breadcrumb that facilitates the navigation.

<img width="477" alt="Screenshot 2024-03-14 at 16 37 37" src="https://github.com/projectatomic/ai-studio/assets/1636769/0c272e51-57f1-4dde-a86a-c2f513873fee">

We are missing it for Recipes:
<img width="569" alt="Screenshot 2024-03-14 at 16 37 52" src="https://github.com/projectatomic/ai-studio/assets/1636769/989ffeb5-b436-4872-b981-26f8b192a844">

We are missing it for Models:
<img width="397" alt="Screenshot 2024-03-14 at 16 38 38" src="https://github.com/projectatomic/ai-studio/assets/1636769/cdf4c21e-a86a-4b02-b7c6-4c577aa454be">

We are missing it for Services too.

**Comment by vrothberg** [comment]
@feloy can we close this given #697 merged?

**Comment by feloy** [comment]
fixed by #697
