### ISSUE TITLE
Use left alignment on table columns having text

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#558]
This issue is based on a feedback received by @ekidneyrh

I went to have a look at how it's done throughout the app atm and there seems to be inconsistencies with it. 

![Screenshot from 2024-03-15 10-16-39](https://github.com/projectatomic/ai-studio/assets/87311656/f7b8286d-3b33-4c4d-a743-0780e1ea09ee)

imo the left aligned looks better and that seems to be what is trying to be done throughout

_Originally posted by @ekidneyrh in https://github.com/projectatomic/ai-studio/issues/541#issuecomment-1999351788_

**Comment by slemeur** [comment]
closing as obsolete
