### ISSUE TITLE
Interaction for selecting a new model in the recipe's model swapping is not convenient

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#573]
The interaction to select a different model in the recipe's model swapping is not natural.

When the user clicks on the model, then the application is displaying the model's detail page. And the user can't easily get back to the page previously displayed.
To actually "really" do the model swapping the user has to click on the select button which is not very convenient at the moment

**Comment by vrothberg** [comment]
I agree.  When clicking on the selection "button", the model gets selected ...

![Screenshot 2024-03-27 at 16 48 35](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/55e8c82f-971e-429c-9a69-2e08753f8cb9)

... but when clicking at the right side of the button (e.g, on the name), I see the description of the model but cannot navigate back
![Screenshot 2024-03-27 at 16 48 46](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/0547bd8a-0ea4-4493-845f-e8657a9d5f36)

@slemeur @axel7083 @benoitf, do you have ideas how navigate back?  An alternative could be a pop up when hovering over the model but a "back" button may also do the trick.

**Comment by vrothberg** [comment]
Apologies for the noise.  The breadcrumb menu at the top now allows for easily navigating back, so I consider this issue to be fixed.
![Screenshot 2024-03-27 at 16 57 55](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/d53fffb1-8d88-4e9c-a08e-a85905683c85)
