### ISSUE TITLE
No confirmation getting displayed to the end user when testing a new model with a recipe

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#574]
When the user is trying to test a new model with a recipe there is no confirmation asked to the end user. As a result the user doesn't really know if something happened.

We should be displaying a confirmation message to the end user, so that it restarts the AI app with the newly selected model

**Comment by vrothberg** [comment]
I agree.

When starting the chat bot with model A:
![Screenshot 2024-03-27 at 16 53 38](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/4cb7ddac-d41b-45b0-ad8e-4aeebaf3d372)

Now, I change it to model B and check list disappears without guiding the user to restart the App:
![Screenshot 2024-03-27 at 16 53 48](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/443b8fc3-c7aa-4e3e-b819-253443553dea)
