### ISSUE TITLE
Version the catalog format

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#59]

**Comment by axel7083** [comment]
Some consideration we might want to have while writing the catalog specifications is how we specify the models information.

We probably need to find a way, since the models is provided by the catalog, to have more informations to get back to source, than just the download url.

## Models registry

### Hugging face

For example looking at hugging faces hub api to get models details we get 

```json
    {
        "_id": "621ffdc136468d709f17debc",
        "id": "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext",
        "likes": 143,
        "private": false,
        "downloads": 92815,
        "tags": [
            "transformers",
            "pytorch",
            "jax",
            "bert",
            "fill-mask",
            "exbert",
            "en",
            "arxiv:2007.15779",
            "license:mit",
            "autotrain_compatible",
            "endpoints_compatible",
            "region:us"
        ],
        "pipeline_tag": "fill-mask",
        "library_name": "transformers",
        "createdAt": "2022-03-02T23:29:05.000Z",
        "modelId": "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
    },
```

### MLflow

> MLflow is an open source platform to manage the ML lifecycle, including experimentation, reproducibility, deployment, and a central model registry.

They are providing model informations in a similar way than hugging face see [RegisteredModels](https://mlflow.org/docs/latest/rest-api.html#registeredmodel)

**Comment by lstocchi** [comment]
I don't know if i misunderstood it yesterday but i thought we were going to add the version to the ai-studio.yaml file? 🤔 So if in future we add any breaking changes we can check the versioning and we know how to parse it?

But, by reading the title, it says catalog so i'm a bit confused.

**Comment by lstocchi** [comment]
@axel7083 maybe it's more related to https://github.com/projectatomic/studio-extension/issues/45

**Comment by axel7083** [comment]
> I don't know if i misunderstood it yesterday but i thought we were going to add the version to the ai-studio.yaml file? 🤔 So if in future we add any breaking changes we can check the versioning and we know how to parse it?

@lstocchi  I think this is the issue related to the ai-studio.yaml https://github.com/projectatomic/studio-extension/issues/19 

> @axel7083 maybe it's more related to #45

The thing is, we need to know where the models came from for https://github.com/projectatomic/studio-extension/issues/45, I cannot get metadata if I do not know where the models came from. 

Currently in the catalog we are saving a raw url to download it, this probably need to be changed as peer my message above. We need to provide the origin of the model.

**Comment by axel7083** [comment]
This added version to the `ai-lab.yaml` format, but not the catalog / user-catalog.
