### ISSUE TITLE
Transfer repositories to containers organization

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#592]

**Comment by axel7083** [comment]
could be done at repository level during the transfer https://github.com/projectatomic/ai-studio/issues/571

**Comment by axel7083** [comment]
Do not forget to change https://github.com/projectatomic/ai-studio/blob/266e9870c243bd46909d5ac54384462f4b8af02b/packages/frontend/src/pages/Dashboard.svelte#L10

**Comment by benoitf** [comment]
it looks like the Dashboard link is not there anymore so can close this issue about the transfer being done

renaming is part of https://github.com/containers/podman-desktop-extension-ai-lab/issues/571
