### ISSUE TITLE
Recipes: not indicated which models are downloaded

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#623]
When choosing/selecting a model for an AI App in the Recipes Catalog, the menu displaying the models does not indicate which models are already on disk/downloaded.  In my case below, two of the models haven already been downloaded but I need to go back to the Models menu to check which of them they are.

Displaying downloaded models in the AI App menu would help me pick the ones I want to try out.

## AI App models menu
![Screenshot 2024-03-21 at 10 55 55](https://github.com/projectatomic/ai-studio/assets/11679875/ade746c7-acc1-4540-8264-6aba1ee4b5eb)

## Models menu
![Screenshot 2024-03-21 at 10 57 32](https://github.com/projectatomic/ai-studio/assets/11679875/4f3187fa-595b-4644-98b4-53205f965878)

**Comment by jeffmaury** [comment]
Not sure to clearly understand: do you want a visual indicator that the model is downloaded or do you want to filter the list ?

**Comment by vrothberg** [comment]
> Not sure to clearly understand: do you want a visual indicator that the model is downloaded or do you want to filter the list ?

Apologies for being vague.  I am looking for a visual indicator in the list, so I can see directly which model is on disk.

**Comment by vrothberg** [comment]
Looking at the screenshots in https://github.com/containers/podman-desktop-extension-ai-lab/pull/714, we could add the same green icon so we have a consistent experience?

**Comment by axel7083** [comment]
> Looking at the screenshots in #714, we could add the same green icon so we have a consistent experience?

Yes, but the size of the table is smaller, and we may want to move away at some point of having duplicates table ?

**Comment by vrothberg** [comment]
> Yes, but the size of the table is smaller, and we may want to move away at some point of having duplicates table ?

The icon could be smaller in a smaller list.

> My argument: starting a Recipe should have a similar UI than creating a Playground or Model Service, with a list of models to select from, with one by default

Ah, I see what you mean.  So it should be drop-down menu instead?

**Comment by axel7083** [comment]
> > My argument: starting a Recipe should have a similar UI than creating a Playground or Model Service, with a list of models to select from, with one by default
> 
> Ah, I see what you mean. So it should be a drop-down menu instead?

Maybe, I am not sure about the UX design, but it feel weird to me that the playground and the model service have a didicated page for creation, where the recipe is a mixte of selecting a model in a tab, and then clicking on a play button.

**Comment by vrothberg** [comment]
I like the drop-down menu but it lacks potentially useful information.  The recipes list shows the repository and license but not the size.

**Comment by slemeur** [comment]
I think this is indeed inconsistency: https://github.com/containers/podman-desktop-extension-ai-lab/issues/623#issuecomment-2022798730 
In some cases, that would be fine (the dropdown), but otherwise, yeah that is something we should be careful.

cc @ekidneyrh
