### ISSUE TITLE
Some models need their Model Service to be deployed with the parameter `--chat_format openchat` 

### ISSUE THREAD

**Issue by MichaelClifford** [containers/podman-desktop-extension-ai-lab#628]
The following models need to their Model Service to be deployed with the parameter `--chat_format openchat` 

* Merlinte-7b-GGUF
* Cerebrum-1.0-7b-GGUF
* dragon-mistral-7b-v0

Without that they will not generate correct outputs.  

<img width="1024" alt="Screenshot 2024-03-21 at 11 51 44 AM" src="https://github.com/projectatomic/ai-studio/assets/4494906/d2246daf-1d58-444d-9faf-d002938a193b">

**Comment by MichaelClifford** [comment]
Good question @vrothberg. There is usually something in the model's readme, but I don't think there is any reliable attribute to programmatically define this. 

I think the long term solution would be to add a form to the playground deployment page that exposes some of the runtime parameters. 

```
 python -m llama_cpp.server --model ${MODEL_PATH} --host ${HOST:=0.0.0.0} --port ${PORT:=8001} --n_gpu_layers ${GPU_LAYERS:=0} --clip_model_path ${CLIP_MODEL_PATH:=None} --chat_format ${CHAT_FORMAT:="llama-2"}
```

**Comment by axel7083** [comment]
cc @jeffmaury

**Comment by jeffmaury** [comment]
We have the plan to add an additional `type` field to the model descriptor in order to support other kind of cnversation (vision,...). Could be based on that or through additional model parameters that are not there for now. What are the recipes that are impacted ?

**Comment by MichaelClifford** [comment]
@jeffmaury All of the recipes that use the playground image along with the default llama_cpp.server parameters (`--chat_format llama-2`) will be affected if they use one of these 3 models.

**Comment by axel7083** [comment]
Fixed by 
- [x] https://github.com/containers/podman-desktop-extension-ai-lab/pull/868
- [x] https://github.com/containers/podman-desktop-extension-ai-lab/pull/904
- [x] https://github.com/containers/podman-desktop-extension-ai-lab/pull/928
