### ISSUE TITLE
Revamp Playground header

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#666]
<img width="572" alt="Screenshot 2024-03-25 at 11 48 16" src="https://github.com/projectatomic/ai-studio/assets/1636769/fe238def-da0b-4ccc-8cfa-7a05f551c128">

**Comment by lstocchi** [comment]
@ekidneyrh i cannot find the mockup on penpot. Any idea where it is? I think I looked at every folder in the penpot ai-lab project. BTW, if you can clarify me two points i don't need to find it. 

The first is about the icon to the left of the model name, the purple S.. AFAIK Mistral has a different icon, so i don't get the meaning of it. Should i use the 'S' (if so, where can i find it?) for every model or we skip the icon for the moment (maybe adding `Model: <name model>`)? I'm not even sure we can use the original icon (copyright stuff..). Do you know anything? @slemeur 

Second, this is what we have now 
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/49404737/4a04f2a8-eb71-4204-9309-5019d3d98ea9)

How should i handle the "Model Service Running" element which is not in the mockup above? Do i completely remove it and I use the left green/red/gray square to display the state of the playground or i keep what we have now without adding the square to the left of the title? Maybe putting it below the delete button like what we do for the kubernetes pages?

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/49404737/e149938b-1aa3-4a8d-8079-f7f591a04a0d)
