### ISSUE TITLE
UX better navigation bar

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#672]
### Description

The navigation bar tends to have too much elements which are not group together and are at the end misleading. We might want to have a UX call on that matter. (not a priority, but https://github.com/projectatomic/ai-studio/pull/671 made me realise how difficult it can be for user to apprehend the extension with the current nav bar. 

The current navigation bar look like this 

![image](https://github.com/projectatomic/ai-studio/assets/42176370/33b80b0c-5d6a-473f-b705-392d984989da)

### Proposal 

IMO we should create two groups, AI Apps, and Models. I made a mockup to illustrate my view on the matter

![image](https://github.com/projectatomic/ai-studio/assets/42176370/45fc6b97-7ea8-4829-a69e-c26e6b080e41)

I feel like the icons provide easy understanding for what do what. I am open for better wording, as I feel `running` or `catalog` might not represent good enough what they are showing.

**Comment by axel7083** [comment]
@ekidneyrh

**Comment by ekidneyrh** [comment]
@axel7083 I like the idea! I wouldn't have the indentation, as the icons push the text to the right anyway. I'd also have the same icon for catalog to avoid confusion. I think if they are very different things maybe rename one of them? I'd love a playful icon for Playground ~ maybe a game piece to make it more fun! But I understand the use of the speech bubble. 

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/a533b9a1-7e2d-4e2c-8fb0-15dfe9fde30e)

**Comment by axel7083** [comment]
> @axel7083 I like the idea! I wouldn't have the indentation, as the icons push the text to the right anyway. I'd also have the same icon for catalog to avoid confusion. 

I really like the book icon !!

> I think if they are very different things maybe rename one of them? 

I don't really know how we could rename the catalogs, they are technically both of them, the `Models Catalog` and the `AI Apps Catalog` a list of items that are available and can be use. Not sure how to improve the naming maybe @vrothberg has some ideas ?

> I'd love a playful icon for Playground ~ maybe a game piece to make it more fun! But I understand the use of the speech bubble.

I don't really like the `fa-message` actually, but I tried to have something that would allow the user to quickly understand what it is
 
| fa-puzzle | fa-message | fa-stack-exchange | fa-comment | fa-comments |
| --- | --- | --- | --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/33270465-2a3e-4cdd-ac8a-7cd3584e4eea) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/67a554c0-c9b0-4ef6-85e2-93cd58e7026c) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/d0ceb622-b3a3-4ed5-9c2f-47175431c403) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/a590fb8c-75bf-4bd2-b645-d9535634d633) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/b7a15644-934e-46ac-8546-6fb6afdff56a) |

**Comment by slemeur** [comment]
I'd like to still call the first Catalog "Recipes Catalog", as I think it better convey the message of what those are. 

Also, I think the header of "sections", we should use capitalized letters.

I'm not a big fan of having two rows of icons as I think it is quite disturbing and increase the width used in the screen. But that is probably a personal point of view.

**Comment by axel7083** [comment]
> I'd like to still call the first Catalog "Recipes Catalog", as I think it better convey the message of what those are.
>
> Also, I think the header of "sections", we should use capitalized letters.
>
> I'm not a big fan of having two rows of icons as I think it is quite disturbing and increase the width used in the screen. But that is probably a personal point of view.

@slemeur thanks for your feedback, here is are updated screenshots with the comparison with/without the icons

| With icons | without icons |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/e1bc5f12-56d2-495b-8350-4f23b7ad949f) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/cbc3fbf6-9c8e-4257-b59a-6841ee38d335) |

I have a personal preference for the one with icons as it add some kind content, and occupy the empty spaces, moreover I feel like it is giving some hints to the user to easily understand what section is for what. But that's also my personal point of view!

**Comment by ekidneyrh** [comment]
If we go without icons, we could add a line in as a visual divider to separate  the two sections and add in more spacing

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/814e3bf6-b3b9-4d58-b03d-7195525242a1)

**Comment by slemeur** [comment]
let's go with icons
