### ISSUE TITLE
AI Apps don't navigate back to the recipe

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#688]
At the present, there is no easy way to get back to the recipe when looking at currently running AI Apps. This step is part of the desired e2e experience and aids in restarting the App with another model.

![Screenshot 2024-03-26 at 10 22 41](https://github.com/projectatomic/ai-studio/assets/11679875/fc3a3cc4-25c9-4fea-a204-b98d0b2cb735)

**Comment by slemeur** [comment]
I think adding an action button that redirects the user to the recipe would be sufficient.
(with the book icon used in https://github.com/containers/podman-desktop-extension-ai-lab/issues/672)
