### ISSUE TITLE
Improve model's row in the list of models

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#701]
In default podman-desktop window size on my screen (large screen), this is the models page. This is not clear nor readable 

![image](https://github.com/projectatomic/ai-studio/assets/42176370/4637f348-e712-4636-9c8f-2f684507e09a)

cc @feloy @slemeur 

**Proposition:**

Use the same pattern with "2 lines" as we have on containers:
<img width="1069" alt="Screenshot 2024-03-25 at 11 29 33" src="https://github.com/projectatomic/ai-studio/assets/1636769/59be4d75-0533-4c0b-818f-7f87a6403636">

IMO, the information which could go on a second line would be:
- HW Compatibility
- Registry
- License

And to be consistent, we would eventually display them using "labels" from the model serving
<img width="855" alt="Screenshot 2024-03-25 at 11 31 24" src="https://github.com/projectatomic/ai-studio/assets/1636769/f0590c9f-b5d1-4a17-a109-2beca73a45ef">

**Comment by slemeur** [comment]
Yeah, that was part of the comment here: https://github.com/projectatomic/ai-studio/issues/479#issuecomment-2017684480

**Comment by slemeur** [comment]
added the proposal to the bottom of the issue
