### ISSUE TITLE
Update hardcoded repository url in dashboard

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#720]
See https://github.com/containers/podman-desktop-extension-ai-lab/issues/592#issuecomment-2014802713

**Comment by benoitf** [comment]
not sure why you open a new issue
as commented in the issue https://github.com/containers/podman-desktop-extension-ai-lab/issues/592#issuecomment-2014802713

the link is no longer there in the updated Dashboard page
https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/packages/frontend/src/pages/Dashboard.svelte

**Comment by axel7083** [comment]
> not sure why you open a new issue as commented in the issue [#592 (comment)](https://github.com/containers/podman-desktop-extension-ai-lab/issues/592#issuecomment-2014802713)
> 
> the link is no longer there in the updated Dashboard page https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/packages/frontend/src/pages/Dashboard.svelte

Oh I went too fast and did not read the full conversation. I was not aware that it has been removed
