### ISSUE TITLE
Bad display of the CPU "badge"

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#739]
The CPU badge is missing its right shape to close the badge

<img width="1251" alt="Screenshot 2024-03-29 at 10 22 40" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/1636769/02e7092b-d4fd-44a0-9f13-9198763bf0ed">

**Comment by axel7083** [comment]
I do not have the same on my computer, that's weird

![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/bd4f9343-5a8b-45b0-a257-0c4198038646)

We can still increase a bit the width to be sure I guess

**Comment by slemeur** [comment]
Yeah, I did not catched that in your previous recording.
Even when I increase the application screen width - I have the same behaviour
