### ISSUE TITLE
feat: ensure version of podman desktop is >=1.8.0

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#765]
We currently have no mechanism ensuring the extension is running in version of podman desktop above 1.8.0. We are using a lot of specific apis which are only available in version 1.8.x.

We need to have a basic check ensuring the requirements are met.

**Comment by deboer-tim** [comment]
Extension container files typically have `io.podman-desktop.api.version=">= 1.8.0"` (AI Lab says >=1.7.0) and package.jsons list API dependencies. Shouldn't we have one path and solve this once in Podman Desktop vs every extension being loaded and having to put in a check?

**Comment by benoitf** [comment]
to me it's a nice thing (not the recommended one) as even if we add that check in Podman Desktop like 1.10 people might try the extension on previous versions of Podman Desktop that doesn't implement the check

it's like a quick win.
