### ISSUE TITLE
chore(inference): container image 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#767]
We currently are using the following container image
https://github.com/containers/podman-desktop-extension-ai-lab/blob/1882d0c6e1fc30d90a1f65b190d721dc93459255/packages/backend/src/utils/inferenceUtils.ts#L36-L37

But on the [containers/ai-lab-recipes](https://github.com/containers/ai-lab-recipes) repository, the following image is build from the CI `quay.io/ai-lab/llamacpp-python:latest`

should we use the one from the CI ? I am not sure to fully understand

**Comment by jeffmaury** [comment]
The recipes uses their own images for the inference server, AI Lab has its own built images. They should remain separate for the time being as we might want to optimize them in the near future
