### ISSUE TITLE
UX: List tagging concept design for recipe containers

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop-extension-ai-lab#77]
Name your app, add a tag for the app to the containers in it

Right now we can't really group the containers of a recipe together - they won't necessarily be part of a pod because the container that serves the model may be involved in multiple different applications. 

So the idea here was to mock up something like a tagging system and the containers of a related recipe could be tagged and we could group them by tag?

**Comment by slemeur** [comment]
closing as addressed in other issues
