### ISSUE TITLE
Provide illustrations for the Dashboard page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#784]
In order to make the dashboard looking a bit more vibrant, we would benefit from having illustrations.

![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/1636769/afbbc6f9-332b-4600-8159-dc412977a240)

- Maybe, having a small image at the top, with seals and exploring AI.

- Icons for each of the sections (with colors?)

**Comment by ekidneyrh** [comment]
For this I got inspiration from robots since it's a chatbot. These are some inspo pics:
![inspo-ai-lab-banner_Page 1_copy_1](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/cc549389-9d5f-4dcc-b4b3-7a7ec6892e5a)

 I have two variations: one where seal is a complete robot and the other is the seal with a robot helmet on. The other seals could be there watching him, or it could just be the one robo seal. Here's a rough idea of what that would look like.
![inspo-ai-lab-banner_Page 2_copy_1](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/93a2965d-44a9-4cfc-836f-8a6a4a6183fd)
![inspo-ai-lab-banner_Page 3](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/76cb4cf0-ea17-4b8f-985d-87bdc37db821)

If something like this is too detailed, it could be a line illustration. WDYT?

**Comment by axel7083** [comment]
Thanks you very much for the designs! Love to see the different inspiration and variatations 👍 

> For this I got inspiration from robots since it's a chatbot. 

For AI-Studio, we are a bit focus on chatbots with the playgrounds, but that's not going to be the full focus in the long term I guess. 

> I have two variations: one where seal is a complete robot and the other is the seal with a robot helmet on. The other seals could be there watching him, or it could just be the one robo seal. Here's a rough idea of what that would look like.

I personnally really like colors in general, and feel like the first one is a bit too gray, and the eyes are a bit scary with the full translucent green ahah.

I remembered using the images bellow, and I what I really like about this rocket podman illustration is the illusion of movement, we have a feeling we are going forward, (to the stars 🚀!) which would probably be the kind of feeling I would want to transmit with AI Lab. 

![75aa5258-9a82-8002-8003-85627e4405c1](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/71cc1302-d568-487d-ab58-13b7a85fbc0b)

> If something like this is too detailed, it could be a line illustration. WDYT?

I have a preference for the second one, with the robot helmet, as it has less details than the first, and the colors are easier on my eyes (personal preference).

**Comment by slemeur** [comment]
Good job @ekidneyrh ! The two variations are looking really cool.

I have a preference for the first one which looks more like a robot that is going to help the other seals. I can see ideas around that robot doing chemistry in the lab... 

On the second one, the helmet looks a bit more "toy-ish".

**Comment by jeffmaury** [comment]
Like the first one, seems happy to help

**Comment by benoitf** [comment]
I also like the first variation and how it renders in the dashboard page

**Comment by feloy** [comment]
I really like the first one too

**Comment by ekidneyrh** [comment]
Thanks everyone for the feedback, I'll get working on vectorizing :)

**Comment by ekidneyrh** [comment]
Spent time today vectorising the first version of the drawing above. Here's currently what I have for robo seal:


![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/917f365a-4952-483f-a1fc-13cc85065c92)

And for the banner I'm plating around with the placement of the seals and the gradient behind them. 


![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/91f4fbad-1ad3-456c-a6cf-9c96395bae21)



![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/a0ccc1ad-0418-406b-a720-982af9fd6e39)

**Comment by slemeur** [comment]
For me, the initial iteration was working nicely. I liked the "subbtle" other seals.

**Comment by ekidneyrh** [comment]
> For me, the initial iteration was working nicely (and better). I liked the "subbtle" other seals.

I can do up a version with just the outlines for the other seals.

> The eyes' color of the robo seal was looking more "modern" and "robotic"

I pulled the current green from the podman colour palette, but I can revert to the previous colour.

Thanks for your feedback!!

**Comment by slemeur** [comment]
Thanks Emma for the work on these illustrations.

We'll need to ensure we have consistency into AI Lab and I'd like to list the other illustration we would need. Here is the list, along with some ideas (but of course, other ideas are welcomed)
- [ ] **Recipe Catalog:** Maybe the robo seal in a library
- [ ] **AI Models:** Here will need to figure out a way to illustrate the models
- [ ] **Playground:** Maybe seal juggling with models 
- [ ] **Model Serving:** Maybe a robo seal doing plumbing between an application and a model

Also, we have a couple of icons which would need to be adjusted:
- [ ] Icon for AI Lab
- [ ] Icon in the left side bar (maybe should just be a bigger version of extension's icon (it could also just be the head of the robo seal)

**Comment by ekidneyrh** [comment]
Updates! 

I made the seals more subtle by changing them to monotone. I tried it out with both just the stroke and by fill. The fill looks better IMO, but I included it to show what it would look like.


![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/2328de0d-09a7-486d-93d7-7b2364f3c823)

![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/c7c7edff-47e7-4855-a4ee-c07edca83469)

![Image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/3c515a46-f4d0-4ff0-807c-39e21a759b50)

I also changed the green in the robo seal's face to match the greenish blue in the initial sketch. :) Let me know what you think

**Comment by vrothberg** [comment]
I love it!  Great work, @ekidneyrh !

**Comment by axel7083** [comment]
Love to see the update 👍 I really like the new version of the seal with the colors ajustement ! I just have some question/interrogations

I was wondering, why the gradient ? Compared to the Podman Desktop Dashboard, where we have clear banner with proper rounded corners visible with a background making a nice contrast as shown in the screenshot bellow the clear background and the gradient makes it a bit fading too much. I would have some preference to have something similar for the consistency.

<img width="1096" alt="image" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/68a1dabd-b47c-4dbc-97b0-a7c3edeefc26">

Also I was wondering why the banner is only filling some of the width, since there is no _clear end_ with its transparent background it feel odds to have it finish in the middle of the screen.

**Comment by slemeur** [comment]
I think the mascot was looking simpler on the initial illustration. the robo seal with the additional "dots" are making me feel it has 4 eyes. I actually think it was looking simpler on the first illustration.

I prefer the stroke design - which is more subtle. (we may want to add sea weeds to fill the space too)
And also, I think we could just remove the purple gradient for simplicity.

**Comment by ekidneyrh** [comment]
> I was wondering, why the gradient

Thanks for the feedback! I chose the gradient to make the robo seal look shiny and new. 

I had just plopped it into the mockup to seem roughly what it would look like but I agree with being consistant with the rounded corners! I'll fix that. 

I wanted the right to be transparent so it blends in to the bg for more sublety but I can see that it's not working. I'll  remove the grandient and choose a diff bg colour for more contrast.

**Comment by ekidneyrh** [comment]
> I think the mascot was looking simpler on the initial illustration. the robo seal with the additional "dots" are making me feel it has 4 eyes. I actually think it was looking simpler on the first illustration.

Lol I can get rid of that. Yah I'll rework it some more :) 
> I prefer the stroke design - which is more subtle. (we may want to add sea weeds to fill the space too) And also, I think we could just remove the purple gradient for simplicity.

Good idea on the seaweed!

**Comment by ekidneyrh** [comment]
I know we said to get rid of the gradient, but just wanted to include an option with a more subtle one bc I think it looks nice. Also included the same graphic without the gradient. I added in more sea things and some background texture to make it less flat. Also changed the background colour to a dark blue to replicate them being in the sea. I think it looks better that the grey as it adds more dimension.![g1748](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/ef034fb2-f07e-4ead-b7b1-ec36847f597a)
![g941](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/9a5021e3-4e20-4e83-8f10-6be69215406d)

Here it is placed in the mock-up.
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/6a0d7f65-bd9e-45a1-afac-a834537eabb5)

In case we hate the two background 'mounds'(?), here it is without them:
![rect26](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/6621c8d0-be36-4eab-adc4-bd70a53065f7)

WDYT?

**Comment by slemeur** [comment]
This is looking really great @ekidneyrh ! 
I like the first one!

**Comment by axel7083** [comment]
> ![g1748](https://private-user-images.githubusercontent.com/87311656/322791738-ef034fb2-f07e-4ead-b7b1-ec36847f597a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjc4NTksIm5iZiI6MTcxMzI2NzU1OSwicGF0aCI6Ii84NzMxMTY1Ni8zMjI3OTE3MzgtZWYwMzRmYjItZjA3ZS00ZWFkLWI3YjEtZWMzNjg0N2Y1OTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDExMzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1Y2ZhYTNjNjZmNmNmNWQ1MGQwMGY3OTA5MGY1YjMwOWRkNjFmMDA4MjA2ZjM3Y2U1ZDdmODk0NTNmMGIwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H8MpcU7rLfUgeRpzSSxMUvpQucrERaPp1HySAyCq5zo)

Love it!

**Comment by ekidneyrh** [comment]
Thanks :) Here's a zip with the first one in SVG and PNG format. [AI-Lab-illustration-dashboard.zip](https://github.com/containers/podman-desktop-extension-ai-lab/files/14997444/AI-Lab-illustration-dashboard.zip)

Is there another place I should upload these for safe keeping?

**Comment by ekidneyrh** [comment]
[AI-Lab-illustration-dashboard-new.zip](https://github.com/containers/podman-desktop-extension-ai-lab/files/14998858/AI-Lab-illustration-dashboard-new.zip)
 sure thing :)

**Comment by axel7083** [comment]
Closing as design approved by @slemeur thanks @ekidneyrh ! 🚀
