### ISSUE TITLE
ai.json updates may not be seen by users using a custom catalog

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop-extension-ai-lab#792]
If we update the ai.json file and release a new version of ai-lab, all users that rely on a custom `catalog.json` will not be able to see the updates made by us, bc ai-lab will still point to the custom catalog.
We should change how the custom catalog + ai.json work

**Comment by axel7083** [comment]
My suggestion is to have a custom `user-models.json` file only containing the user's models, that we would append to ours.

I also firmly believe that the models and recipes catalogues should be splited to give more flexibility.

**Comment by slemeur** [comment]
How this is impacted, when a user is "importing" a model?

**Comment by slemeur** [comment]
After getting details, this is going to affect a user who has imported his/her own model.
- User imports a model, AI Lab will create a new catalog.json file in a user's directory
- At new restarts of AI Lab, it will check if a user defined catalog.json file exist. If so it will use that one.
- There is no mechanism in place to consolidate the user's defined catalog.json and the file provided out-of the box with AI Lab (and its update)

Is the understanding correct?

**Comment by axel7083** [comment]
> Is the understanding correct?

Exactly ✅

**Comment by slemeur** [comment]
Then, in this case, I think it's something we have to manage before the 1.0 release.

**Comment by axel7083** [comment]
## solution proposal

Instead of copy past the content of the catalog in a new one, that will be read by default. We should combined them.

So we always have the _native_ recipes, models and catalog, while adding the one of the user. This would require little change in the `CatalogManager`. 

cc @jeffmaury @lstocchi any opinion ?

**Comment by lstocchi** [comment]
> ## solution proposal
> Instead of copy past the content of the catalog in a new one, that will be read by default. We should combined them.
> 
> So we always have the _native_ recipes, models and catalog, while adding the one of the user. This would require little change in the `CatalogManager`.
> 
> cc @jeffmaury @lstocchi any opinion ?

So having the default catalog + a custom file with the imported models and merge them? Sounds good to me 👍

**Comment by jeffmaury** [comment]
> > ## solution proposal
> > Instead of copy past the content of the catalog in a new one, that will be read by default. We should combined them.
> > So we always have the _native_ recipes, models and catalog, while adding the one of the user. This would require little change in the `CatalogManager`.
> > cc @jeffmaury @lstocchi any opinion ?
> 
> So having the default catalog + a custom file with the imported models and merge them? Sounds good to me 👍

Yes I think merge is the best solution
