### ISSUE TITLE
Create CICD pipeline to run AI Studio extension e2e tests.

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop-extension-ai-lab#794]

**Comment by odockal** [comment]
@ScrewTSW I have prepared PR for tackle this issue, probably. Just to make sure, this issue is to cover what exactly? The PR I have provided runs extension e2e tests on demand and after merge into main of this repo and runs on Linux (ubuntu) on GHA CI and also install Podman 5.

**Comment by odockal** [comment]
CI Workflow for e2e tests on linux now runs on demand and after push to main. https://github.com/containers/podman-desktop-extension-ai-lab/actions/workflows/e2e-main.yaml
