### ISSUE TITLE
Unable to know which ai-lab.yaml file is used

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#813]
From the page for a recipe, it is not possible to know for the user which ai-lab.yaml is used for the recipe, and so, which are the sources which are used for the recipe.

It is especially true for the repository used for the recipes, which is a common repository for all recipes.  

When using the "Open in VS Code", the root of the respotory is opened, it would be interesting to open the directory on which the ai-lab.yaml file is located, and/or open the ai-lab.yaml file.

Also, we could display the path of the ai-lab.yaml file in the UI

**Comment by axel7083** [comment]
Probably resolved ? cc @feloy
