### ISSUE TITLE
Downloading model fails when using a user's catalog

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#814]
Steps to reproduce:
- copy https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/packages/backend/src/assets/ai.json to ~/podman-desktop/ai-lab/catalog.json
- go to a recipe page, start the ai App

A local model should be detected, or the model should be downloaded if not present locally, then the images should be built.

When a user's catalog.json file is present, the local model is not detected and is reloaded every time, and the start of the recipe fails before to build the images with an error message 'model is not available locally'

**Comment by lstocchi** [comment]
By trying to replicate it using #771 it works fine. Once merged, we could verify if that fixes this issue as well.

**Comment by feloy** [comment]
> By trying to replicate it using #771 it works fine. Once merged, we could verify if that fixes this issue as well.

I tested #771, after rebasing it to main, effectively the problem is fixed. Thanks
