### ISSUE TITLE
Open in VSCode should open the new "recipes" directory of ai-lab-recipes

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#816]
AI Lab Recipes ships a new "recipes" directory with source for the respective use case (e.g., ChatBot).  To support the e2e user experience, it would be helpful to open the specific directory in VSCode as displayed in the screenshot below:

![Screenshot 2024-04-04 at 11 45 40](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/09849a07-bd93-47b2-817d-62f8a52b2233)

**Comment by slemeur** [comment]
Is this something we can do? @jeffmaury ?

**Comment by feloy** [comment]
same as #813

**Comment by vrothberg** [comment]
I think it's a slightly different use case:  in this one, I want users to be able to navigate to the `make bootc` target.  But opening the recipes directory should achieve both use cases.

**Comment by jeffmaury** [comment]
Yes I had the same feeling, the info is in the catalog so it's doable

**Comment by vrothberg** [comment]
Amazing news, thanks, @jeffmaury

**Comment by vrothberg** [comment]
If possible, it would be great to open the README directly.  This way, the user can directly see and follow the instructions.

**Comment by jeffmaury** [comment]
> If possible, it would be great to open the README directly. This way, the user can directly see and follow the instructions.

I'll check but I think this is default VSCode behavior
