### ISSUE TITLE
UX: Promote Playground to be a top-level ui construct / nav item

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop-extension-ai-lab#82]
Right now the playground is attached to specific models. Instead, it should be a top-level UI construct and maybe have a top-level nav item. This is because we will be able to switch between models on disk on the fly in the playground, so conceptually it shouldn't be attached to specific models.

We should also design it to enable better evaluation rather than just "gut" playing around. We could start by giving a list of models tried and how long the prompt took to return an answer in the UI (maybe reverse chrono.)

**Comment by slemeur** [comment]
done
