### ISSUE TITLE
playground navigation

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-ai-lab#842]
there is an issue around how to navigate back to a recipe,

https://github.com/containers/podman-desktop-extension-ai-lab/issues/688

but I think it applies to playground as well.

I only can use playground chat from "Playgrounds menu and then I have for example Playground 1" for a given Model

but from there I can't click on the model to go to the model details or for example on the model list, it doesn't tell me that there is a running playground (I could have an icon from different locations to the playground)

**Comment by slemeur** [comment]
I'm splitting the issue into two: #845 and #846
