### ISSUE TITLE
Provide ability to navigate to the model details from a playground

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#845]
<img width="444" alt="Screenshot 2024-04-09 at 09 56 15" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/1636769/76e40e46-c5fc-481a-866b-2c8d30e167e7">

Relates to #842, we should make the model clickable and redirecting to the model's details

**Comment by axel7083** [comment]
This overlap with https://github.com/containers/podman-desktop-extension-ai-lab/pull/1101 closing as will be covered by @lstocchi
