### ISSUE TITLE
Clicking delete on a running AI app doesn't provide feedback

### ISSUE THREAD

**Issue by ckyrouac** [containers/podman-desktop-extension-ai-lab#857]
When clicking the Delete Icon in the AI Apps table, it can take some time for the app to be deleted. During this time, there is no indication the app is currently being deleted. On my resource starved machine, the app entry in the table took around 10s to eventually disappear. During that time, I wasn't sure if the delete request worked or not, and almost clicked it a second time. A spinner on the delete icon, or another indication that the delete operation is in progress would be helpful.

**Comment by axel7083** [comment]
Related issue https://github.com/containers/podman-desktop-extension-ai-lab/issues/547
