### ISSUE TITLE
no playgrounds: add explanation what playgrounds are and how to use them

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#877]
User feedback suggests to add a description of what playgrounds are and how to use them.  At the present, we navigate the user to create a new playground but they may not be aware what a playground is.

![Screenshot 2024-04-11 at 11 16 15](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/6d068906-3804-4d02-a6c0-cc3606941a91)

**Comment by slemeur** [comment]
Linking to https://github.com/containers/podman-desktop-extension-ai-lab/issues/271
