### ISSUE TITLE
The service page does not seem to be updated live

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#882]
After a model service is created if you switch to the list page it will say the service is starting but it does not seem to be updated.
Also if you delete a service it also does not seem to be removed

**Comment by axel7083** [comment]
> it will say the service is starting but it does not seem to be updated.

I am able to reproduce, still an issue with svelte I will take a look

> Also if you delete a service it also does not seem to be removed

I do not reproduce

https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/8a1d4840-da91-4e3d-af94-d9c13c8bd652
