### ISSUE TITLE
models page: consider moving available models to the top

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#894]
The list of models can grow quite large which requires scrolling to find all available models.  My gut feeling is that available models should be moved to the top.  After importing a model, I was afraid of something having went wrong because I didn't see it immediately (at the top).

Thinking out loud: maybe we can add another sorting based on availability and make this default?  It would first sort by availability and the two sub-lists by name?

![Screenshot 2024-04-15 at 10 48 44](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/0cbad43d-3f26-4d51-8a47-677a9ad0bafc)

Cc: @jeffmaury @slemeur

**Comment by slemeur** [comment]
Status column has been added and allows this
