### ISSUE TITLE
recipe model selection: clicking on name navigates to model details/page

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-ai-lab#910]
Based on user feedback:

The current behavior when selecting a model for a recipe is that clicking on the name navigates to the details of the model.  The user's expectation was to instead select the model.  Instead, clicking on the name opens the details page of the model and there is no way to go back to the recipe but only to the models page.

I also noticed that when selecting a model, the recipe page jumps back to the top.

![Screen Recording 2024-04-17 at 09 22 35](https://github.com/containers/podman-desktop-extension-ai-lab/assets/11679875/ce6d893e-a0b3-4a0c-8f6f-c5e6334704ea)

**Comment by slemeur** [comment]
Obsolete, as this has changed since the issue was reported
