### ISSUE TITLE
Service model status is not updated when starting it after it was shut down

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-ai-lab#942]
It seems that the state icons for service model do not get updated to Running state when the service model is started up after it was shut down. The icons are in a continues starting/loading cycle.

Steps:
1. Create a service model.
2. Shut down the service model create in previous step.
3. Try to start back up the service model.
4. Notice that the status icons are in permanent starting/loading state.

To note that it seems this is just a graphical issue, if the user tries to make a curl query from the CLI the service model will reply as normal even though in PD it shows as starting/loading.

https://github.com/containers/podman-desktop-extension-ai-lab/assets/106525396/abc71d1c-8dec-4704-87df-5c0c1e6152a7

**Comment by axel7083** [comment]
We are using the podman health check, if you can replicates please copy/paste the container inspect result (from container details page).

And the logs of podman desktop also if possible, it might also be a problem from the frontend of the extension, you can see those by 
- right click on the extension ai lab icon of the navigation bar of Podman Desktop (bellow the kubernetes icons)
- Open devtools

**Comment by axel7083** [comment]
I was able to reproduce

**Comment by ScrewTSW** [comment]
Issue was not reproduced in AI Lab 1.1.0 or 1.1.1, closing.
