### ISSUE TITLE
models page should have an _imported_ tab

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#944]
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/481bc45d-8aa8-474c-9785-64b58f7d3e81)

The imported models of the user are located in `downloaded` which is not really what it is, we should have an imported section.

cc @jeffmaury @slemeur

**Comment by vrothberg** [comment]
👍  good catch!
