### ISSUE TITLE
Adopt SettingsNavItem UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#974]
Depends on https://github.com/containers/podman-desktop/issues/6908

See also https://github.com/containers/podman-desktop/issues/5757

**Comment by axel7083** [comment]
Depends on https://github.com/containers/podman-desktop-extension-ai-lab/issues/1165

**Comment by axel7083** [comment]
This component is not available on 1.10.3, we need to migrate to a more recent version (next) but this is probably subject to change
