### ISSUE TITLE
Services title should be Services not Model Services

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#996]
![Screenshot 2024-04-24 at 8 01 16 PM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6422176/fae46e02-1d23-43ef-8d62-1e68b903f077)

Should be Services as it does not match the side bar name.

**Comment by slemeur** [comment]
I don't think the matching is necessary. 
The left sidebar simplifies the title, so we don't get too long titles.
