### ISSUE TITLE
Should be "Playground" not Playground Environments

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-ai-lab#998]
The title does not match the side bar:

![Screenshot 2024-04-24 at 8 03 17 PM](https://github.com/containers/podman-desktop-extension-ai-lab/assets/6422176/b3d1f5be-b00e-4cf0-b51d-9f87fc3a8721)

**Comment by slemeur** [comment]
I don't think the matching is necessary. 
The left sidebar simplifies the title, so we don't get too long titles.

**Comment by cdrage** [comment]
One thing I just noticed is that the title seems smaller than the other pages?
